### ISSUE TITLE
Item Manager

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#10]
To catalogue game items and associated properties

- [x] research on best way to approach this problem
- [x] create a static item manager controller on a new GameObject and add it to the managers hierarchy 
- [ ] experiment with the small amount of items that are created already (by creating an item component and placing it on the item prefabs, atm there is only the knife but more are being created)
- [ ] develop a public function to access the item and instantiate it with a given Vector2 position
- [ ] develop a way to allow other devs to easily add new items to the item list (maybe just a public array that we can just drag and drop the prefab into the interface of the component for the time being)

Here is some suggestions on how to approach this using a dictionary: http://answers.unity3d.com/questions/155003/item-database.html

**Comment by DooblyNoobly** [comment]
![stackeditems](https://cloud.githubusercontent.com/assets/20813925/20237796/e34a436c-a927-11e6-886c-328d142e2a17.png)

Items are stacked and are grid based in movement aswell. It's probably possible to just add the PhysicsMove component for a quick draft.

**Comment by DooblyNoobly** [comment]
using lists and dictionaries? https://www.youtube.com/watch?v=qVgrJkdampw

**Comment by DooblyNoobly** [comment]
@tfmeads updated this to provide some clarity

**Comment by tfmeads** [comment]
Sorry I haven't been able to contribute anything tangible yet- school and work are keeping me busy. Should have a LOT more free time in the coming weeks. Here's what I have so far on to how we should implement the basic item structure:

The gameplay for the original SS13 varied significantly from server to server due to the modding capabilities. Every server had a different master list of items, tiles, objects, etc. and I'm pretty sure that's something we want to emulate in Unitystation. The list of instantiate-able items in any given Unitystation should be read in from some kind of init file (perhaps in an XML-like format?), the prefabs should be able to be generated on the fly from the data in its corresponding entry. Here's a dummy entry to demonstrate how the concept should work:



    <ItemList>
        <Item>
            <Name> Toolbox </Name>
            <ExamineText> It's a toolbox. </ExamineText>
            <Sprite> .../Assets/Resources/toolbox.png </Sprite>
            <Weapon>
                <BruteDmg> 45 </BluntDmg>
                <BurnDmg> 0 </BurnDmg>
                <AttackSound> .../Assets/Resources/bang.mp3 </AttackSound>
            </Weapon>
        </Item>
        .....
        .....
    </ItemList>

It should be pretty easy to create new items and modify the attributes of existing ones using this method. Unique attributes such as an item's status as a consumable or weapon can be modeled simply by adding the appropriate tag in the XML tree. Specialized controllers should be written to parse the data in the XML tree to be turned into game logic, and I'd assume more advanced things could be modeled by specifying a .cs file to be run. Not entirely sure at this point. But if we want to design US to be easy to scale and build mods for, I think we should design the system this way.

**Comment by DooblyNoobly** [comment]
Yep I like it. The master list will have a simplified name of the prefab and then you can just call that name and it will have the data on actually where the prefab is and instantiate it etc. Then on each item in the prefabs will be a class named ItemAttributes and this will handle the immediate ingame values such as: amount of damage it can do, is it edible, can it fit in the storage01 slot etc. 

BTW if you are working on any managers soon then create a new branch from Lobby-Kitchen as it is the most up to data branch with the current management system. Hopefully I'll have a good enough version to merge with master soon.

**Comment by DooblyNoobly** [comment]
Alright that didn't take long, managed to get a good working version of the lobby and the chat and merged it into master. 

Edit: don't forget to open the Asset Store and download "Photon Unity Networking Free"

**Comment by DooblyNoobly** [comment]
@tfmeads Not sure if you want to carry on with the item pick up --> playersprites functions,But I just wanted to let you know of the  [ItemAttribute class](https://github.com/unitystation/unitystation/blob/master/Assets/scripts/ItemAttributes.cs)  on each item prefab so maybe this can hold the master item int which can then be used with the logic that calculates the associated sprites for righthand, lefthand in PlayerSprites etc.

There is also an [Item UI tracking component](https://github.com/unitystation/unitystation/blob/master/Assets/scripts/Items/ItemUI_Tracker.cs) that is added to each item when it comes into the UI item slots. Maybe this could also hold some information to help with sprites and item info.

**Comment by tfmeads** [comment]
Sure thing. That was actually the next thing on my todo list.

**Comment by kaffo** [comment]
I like the idea of having our items defined in some kind of markup language then parse it code side.
However I think we need a really strong class based system code side too. It's going to be one of the most important/fundamental parts of the game later one when it comes to extending it, so having a solid base now will make/break what we have going forward.
We can discuss further on IRC or here.

**Comment by DooblyNoobly** [comment]
yep, ItemAttributes that sits on the prefabs is the start of it. And the ItemManager will handle the access to most of the item class structure because it is a singleton, so all of the functional components will eventually hang off it (Things that we can't foresee atm).
