### ISSUE TITLE
[features] Laydown shortcut & balancing[Zzz] :zzz: w

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10118]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### What happened?
do this only if the character falls (e.g. after slipping on the floor)
he automatically gets up after several seconds (as was the case a while ago) 

and add a keyboard shortcut to stand up automatically like "K" for "on your knees".

**Comment by AtnerNT** [comment]
Once again, I would rename this issue to: "Laydown shortcut & balancing"

Also to make the PR description more clear (From what I can tell you are suggesting):

"Add a keyboard shortcut to toggle laying down and standing up.
Add the ability for players to stand up automatically after a few seconds of being knocked down."

**Comment by Fr-Dae** [comment]
you say exactly what is above. except that you speak in the imperative rather than in sentences.  :/

**Comment by AtnerNT** [comment]
> you say exactly what is above. except that you speak in the imperative rather than in sentences. :/

I understand there is a language barrier so let me explain the exact difference between the descriptions so you can get a better idea of what I am getting at.
"do this only if the character falls (e.g. after slipping on the floor)
he automatically gets up after several seconds (as was the case a while ago)"

The phrase "Do this only if the character falls" provides no context as to the subject, what is "this". It is fairly unclear what exactly that sentence is addressing. It isn't really clear you are talking that the player should automatically get up only if the player falls. The sentence here:
"Add the ability for players to stand up automatically after a few seconds of being knocked down."
Says the same thing you are right, but clearly states you are talking about the ability to stand up after being knocked down.

**Comment by MaxIsJoe** [comment]
I'm closing this issue due to the following reasons:
- We have discussed this multiple times before in things like the `edible` component discussions on discord, we do not automate player actions. While /TG/ already does this, we have no intention of directly copying every bad decision they've made.
- We don't need to add this since it is already in the game. If you are stunned, you automatically stand up once the stun duration is over as long as you are not interrupted by something or something else knocks you down.
- If you have issues knowing when you can stand up again, #10309 should fix this.
- This sounds like a suggestion for an emote. Emotes already have a button for it, which is \ by default. On top of that, we have the surrender emote, which does the same thing exactly as the "on your knees" thing.
- This is generally a low quality issue that is not useful for anyone.
