### ISSUE TITLE
[BUG] large number of errors, creation of log file of many millions

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#10129]
### There is no other issue reporting the same problem.
- [X] I have searched the existing issues

### Game Version
23.10.11.00

### I was
Server Local Host
HOS
SquareStation

### OS
**OS:** Lubuntu 22.04x64 
**Kernel:** 5.15.0-86-generic 
**Memory**: 16Gio Ram
**CPU**: Intel i7-6700HQ (8) @ 3.500GHz
**GPU**: NVIDIA GeForce GTX 960M 

### What happened?

Hi, I've found a big, dirty bug.
I was on a localhost session to test some uniforms.
- I spawned a lot of characters with the F7 key
- I deleted the two terminal medical (see bug #10132 )
- I deleted the duplicate characters

I organised the generated characters by department, 
and I say to myself "the area is too small, I'm going to make it bigger".
- I use the tiles changer.
- I add windows all around
- I remove the excess walls
- I remove the grids
- I remove excess glass

and then ... the game starts to slow down more and more,
I close firefox, and I look at the logs, 1 361 666 errors ... increasing

https://youtu.be/zkOwdAyUAqQ[

[Player.log](https://mega.nz/file/cpNH3SrC#HmGNjzZKzSRcttBVlxGxxQhy5tUOw6MK0jHLfGrJ3LI) **150Mio**

**Comment by Fr-Dae** [comment]
maybe link to #10131 Shift bubble spam
and maybe link to #10130 admin tool - Deleting a character does not delete the entity

**Comment by MaxIsJoe** [comment]
This issue seems to be fixed, as deleted characters seem to no longer have any checks lingering and they properly despawn now. 
![image](https://github.com/unitystation/unitystation/assets/34368774/5f724e12-a10a-436a-9040-4607d82fb5f3)


https://github.com/unitystation/unitystation/blob/7a1a76908faa17ed6e2f51e2a1a111aced8e4830/UnityProject/Assets/Scripts/Messages/Client/DevSpawner/DevDestroyMessage.cs#L44
