### ISSUE TITLE
Doors close sometimes with player on them

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1110]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
development

# Report

## Expected/Wanted/Requested Behavior
Door detects reliably if there is a person on it.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Go to some doors
2. Walk into them and out
3. eventually, the door will close with the player on it

![image](https://user-images.githubusercontent.com/7312905/42062248-52193db0-7b2d-11e8-8cb9-d4cefddfc6bd.png)

**Comment by bobster707** [comment]
used to happen on the byond ss13 was solved by making the door a solid object while the transition animation was happening and not afterwards.

**Comment by chairbender** [comment]
I've tested this on high ping server and client. I can get it to happen on client only, and even then the client lerps back out of the closed door. Rarely, I can get the client stuck in the door but they can just move to open it back up. It only happens if you enter the door with very specific timing, right when it is about to close. 

I will try to fix the client side cases where the door closes on them.

**Comment by chairbender** [comment]
Per discord discussion about how this should work, in ss13 it is possible to leave a door open by putting a body in it. If door safety is disabled, it is possible to damage a player by closing the doors on them.

Given that, it seems to make the most sense to reopen the door when it closes on a player (unless safety is off, in which case it should hurt the player), rather than rolling back the player position. Try to make it so that we don't have to wait for the door to close completely before reopening it - ideally, the door should just stay open and cancel the closing animation (but this will probably not be possible because the animation will have already started before the server knows the client is occupying the door).

**Comment by chairbender** [comment]
After more research, here's what's happening:
When the door first closes, it checks if anything is blocking it, but it is still possible for a laggy client to go into the door while it is closing. There are 2 cases: 
1. Client enters door after server knows the door is impassable, but before client knows it is impassable. 
2. Client enters door after the close begins but before server marks the door as impassable and before the client knows it is impassable. This is rare but there is a slight delay (.15 s) between when the door close begins and when the server registers the door as impassable, so it is possible (See AirLockAnimator.MakeSolid)

Case 1 is handled by our rollback code - the client will be lerp'd back to their previous position.

Case 2 won't be handled by the rollback code because the client enters the passable tile while the server still thinks its passable. So, for the rare situation that case 2 occurs, we will check and reopen the door if something is blocking it. This affects anything impassable that could be inserted into a door, not just a player.
