### ISSUE TITLE
Use mop to clean up blood B: 50

### ISSUE THREAD

**Issue by aodendaal** [unitystation/unitystation#1158]
# Description
Any player can hold a mop, stand on a tile of blood and use the Activate key to remove the blood.

## Category
Feature Request

**Comment by EmergencyTemporalShift** [comment]
Is there DNA evidence implemented yet? If there is, that's got to be left behind.

**Comment by DooblyNoobly** [comment]
nope thats not in yet. We have a metadata layer that we could put a list of dna and fingerprints on

**Comment by AlexTheM8** [comment]
Mop object has been added to the game, but the script currently needs to be properly coded.

**Comment by DooblyNoobly** [comment]
## Added bounty to this ticket:

 ### Criteria:
 - Finish mop script so that it cleans up blood 
 - Apply the progress bar to the action (see wall deconstruction, there is a generic tile progress bar that can be used for anything)
 - Ensure cleaning is server authoritative 
 - Test in multiplayer

Bounty of 50 usd will be awarded to the contributor on a successful merge of a PR that completes each of the criteria above.

**Comment by badbon** [comment]
Cool I'll probably do this.
