### ISSUE TITLE
Bug: Windoors only work in one direction

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1197]
# Description

For some reason the WinDoors now only work in one direction (unsure of when bug was introduced but I assume it happened with the new matrix changes)

See the gif below:

https://thumbs.gfycat.com/DamagedBeautifulIberianchiffchaff-size_restricted.gif

## Category
Bug

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find a windoor and try to run into it
2. Run into it from the opposite direction
3. Observe the bug

**Comment by Jibbajabbafic** [comment]
I've tried to solve this but it has to do with the matrix changes like you said, and I don't know enough about the matrix system to solve it.

`PlayerMatrixDetector::CanPass` is returning true when it should return false because `!MatrixManager.IsPassableAt( position, position + direction )`  doesn't check the same tile.

Trying to do that with `!MatrixManager.IsPassableAt( position, position )` doesn't seem to work though.

I'll leave this to someone more experienced, hopefully what I've written is helpful.
