### ISSUE TITLE
"Common" Chat name is cutoff

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1248]
# Description

## Category
BUG

## Detailed Bug Report
When choosing the chat channel to talk to, the channels names can be cutoff, e.g. the "Common" chat

## Steps to Reproduce

1. Open chat (T)
2. Choose "Common" chat
3.
![image](https://user-images.githubusercontent.com/7312905/46013599-181a3700-c0cd-11e8-9e15-93edee42595a.png)

## Further remarks

As this could also affect other names, keep the fix general (don't just fix it for the "Common" channel)

**Comment by LauraLaureus** [comment]
I was studying this project for this issue and it seems that:
-> Label is misplaced to left. 
-> When selecting the chat name any space is added at the beggining of the row.

I don't even attempt to do a pull request to this because when i opened the project a dialogue was prompt that states the project is for unity 5 instead unity 2018.2  as the contribution documentation says.

**Comment by badbon** [comment]
@LauraLaureus Just press continue, I don't know why it says that (it did for me too) but it works on 2018.2.
