### ISSUE TITLE
Toggleable items: secure, consistent, easy to create and support

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1249]
# Description

## Current state
We have our first toggleable item: **Welder**.
#### Concerns about Welder code
Client and server code is mixed up. 
That makes client and serverplayer routines inconsistent, therefore it's required to test it twice.
BurnFuel is one common loop, it would be very painful to debug.

Code contains a reference to holding player, it shouldn't be there.
It's clumsy to access and set from outside (see WelderTrigger):
People really shouldn't have to explicitly do [LocalPlayer](https://github.com/unitystation/unitystation/blob/6fbee9ad1855e76dc6ae0dad2ec5b421af40b22a/UnityProject/Assets/Scripts/Items/Tools/WelderTrigger.cs#L15) or [Slot.Item](https://github.com/unitystation/unitystation/blob/6fbee9ad1855e76dc6ae0dad2ec5b421af40b22a/UnityProject/Assets/Scripts/Items/Tools/WelderTrigger.cs#L17) checks for every new item they create

Code uses SyncVars for fuel levels and on/off state.
1) While SyncVars are okayish for rapid prototyping, we shouldn't continue to rely on them:
-it's not 100% reliable (feels like UDP despite any settings)
-it's insecure (sends to everyone)
-new networking layer is on the horizon 
2) Client has information about current fuel level. In this case it's really not required.
Also that update is sent out every decisecond when welder is burning.

#### Suggestions
Item logic (like fuel consumption loop) should be working only on server, and client should only receive toggle updates to switch sprites and animation.

I think it's possible to make it work with NetMessages and UnityEvents.

I'm thinking of some kind of ToggleItemMessage that would:
1) Update all according sprites without need of any kind of `heldByPlayer` fields inside item scripts
2) Invoke some event, i.e. `OnToggle(bool isOn)` that anyone could hook up to

## Criteria of success

- [ ] Separate client and server methods inside item code
- [ ] One unified update message instead of syncvars
- [ ] No need for holding player references inside items by design
Something else?

**Comment by DooblyNoobly** [comment]
It's really a toss up between benefits when choosing between using a SyncVar or a NetMsg.

You have pros and cons with each.

------------------
#### Cons:
With netmessage: You create garbage, and have to manually update new players

With SyncVars (which does update ordered and reliable): You send to all players adding to bandwidth usage and opens up the possibility of others sniffing to gain an advantage (Though with welder fuel amount and onOff property I don't think this information can really be used to create much of an advantage, that is why I considered it a low sec threat). <-- This can all be rectified with network culling but we will wait to see what 2018.4 brings before attempting that.

#### Pros:

NetMsg: Direction communication, less bandwidth, high security, no need for culling

SyncVar: No need to manually update new players, less code, easy to use and debug. 


--------------
So I don't know here, I don't think we should completely dismiss Syncvars in these low security concern areas. But I was really just waiting to see what 2018.4 brings. Maybe they have really cool Proximity Sensors in the works.

The Update every DeciSecond thing was a bit lazy on my part. I will make it update every second. I was also hoping the client can do a bit of the sprite update work instead of always relying on Server (I know that is Taboo but it really doesn't make sense to me to add more bandwidth usage for something that doesn't matter that much, i.e so what if a client hacks his sprites no one else will see it).

In regards to combining the Client and Server stuff with the isServer condition inside BurnFuel this turned out to be the most efficient as you need to see the states a game instance can be in as Client, Server and Hosted instead of Client, Server. I had started with the separated methods when we were chatting and soon found it wasn't going to work with hosted so I combined them. An alternative here would be to register to UpdateManager and separate the methods but I thought that was a bit overkill as all welders would be getting the UpdateMe call from UpdateManager instead of just turning a Coroutine on and off on the item when you need it and from my understanding it is recommended to only have one coroutine running on an object at a time, so I combined them (Hosted scenario two coroutines would of been running if they were separated). Btw sprite changing for the fuel amounts on the welder itself hasn't been implemented yet.

I have a feeling that when 2018.4 comes around there will be a lot of work refactoring the network code and also discovering new ways of handling these concerns, so I think this issue should be visited then. But from my understanding the Unity devs are making sure that transition to whatever comes in 2018.4 from UNet should be relatively easy. Lets wait and see.

**Comment by DooblyNoobly** [comment]
One other thing I forgot to mention. The heldByPlayer was needed so that I could update the actual UI slot of that player with the flame sprites when the user turns it on and off. Also I added a Secondary Image to each UI_ItemSlot for items that have 2 sprites and the UI_ItemSlot will automatically handle all of that when it enters the UI.

Also the server needs to know from welder who is holding it too so that it can sync the inhand sprites. A little flame appears in the inhand when you turn it on and off.

I'm adding more comments to the welder script too for the next pr.

**Comment by fomalsd** [comment]
Netmessage garbage is really negligible unless you send large strings or spam them like crazy (every frame).
The way I proposed network updates for toggleables is just sending on/off updates, client manages sprites/animation himself depending on received event.

I wouldn't hold my breath about Unity's own culling:
If it's range based then hackers would still know what's happening behind the walls,
also imagine this: you are presented with two welders on the floor, one empty and one full. 
they look identical. which one would you pick? hacker would certainly pick the full one as he's drawing fuel amount over each welder because it's there. 
Point is: if you're sharing some extra fields, they should either be public for everyone (different sprites for empty/full), or hidden from everyone unless examined explicitly.
Yes, in this case it's not a big deal, but this system is meant to scale, and if every item will be this insecure it'll end up bad.

I'd rather rely on our own message culling implementation when we get there.

About client/server routine separation, just have two loops: 
one for burning fuel on server (without updating sprites), and another one for clientside animation that would work when "On" update is received

Also about heldByPlayer: it would be better if this logic would be common and run in ToggleItemMessage's Process() method on clients. That message could have an optional heldByPlayer field.

**Comment by donovanhubbard** [comment]
Please make an interface or an abstract class for this so its reusable.

**Comment by chairbender** [comment]
Would you consider this fixed now that IF2 is in place?

**Comment by fomalsd** [comment]
Yeah, I think so. We don't have a template for toggleable items, but IF2 and IS2 provide a robust way to implement all kinds of items
