### ISSUE TITLE
Host-Checkbox appears after restart / being kicked

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1250]
# Description

## Category
BUG

## Detailed Bug Report
After steam auth wasn't successful, you get kicked out and land on the login screen. However now the "Host"-Checkbox for self-hosting appears.

## Steps to Reproduce
This is difficult to reproduce as it would only happen when being kicked, but the fix will probably be to check the login window every time when shown, if the checkbox should appear or not.

**Comment by fomalsd** [comment]
Encountered that too, also it appears that you cannot actually host a server in that case, even if you tick that checkbox! (probably due to `isForRelease` being true)
It's relevant to steam releases that are "for release" and can be reproduced by launching game executable directly from steamapps folder with steam itself turned off

**Comment by chairbender** [comment]
I tried reproducing this by adding logic which kicks the client as soon as they try to spawn (in SpawnHandler.RespawnPlayer).

When they are kicked due to this, I don't see this issue. I'll see if this still happens on the steam build.

Maybe it only happens when they are kicked due to steam auth issues but not when kicked at other times.

**Comment by chairbender** [comment]
I can't reproduce this anymore on the steam version. However, it still does appear buggy when being disconnected when using the Steam version. You can sometimes get to the job selection screen, then when you are disconnected the selection screen stays up (or the team selection screen). When you try to log back in the host checkbox is not there but the selection screen is and the UI gets even more messed up.

Will look into fixing that.
