### ISSUE TITLE
closing and opening a locker on yourself makes wall objects visible

### ISSUE THREAD

**Issue by Fishfish458** [unitystation/unitystation#1571]
# Description
Player can see wall objects on the other side of walls after closing and opening a locker on themselves
## Category
BUG

## Detailed Bug Report
[example](https://imgur.com/uaL0Dij)
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. get in a locker and close and open the door rapidly
2. notice some objects flicker into existence

**Comment by Fishfish458** [comment]
this bug was discovered while looking into #1504 and i'm starting to think the two are actually related to the same issue.

**Comment by coolcat1711** [comment]
![image](https://user-images.githubusercontent.com/3880412/53700349-35aba500-3dbf-11e9-8425-ecbe43289afb.png)

Was able to pause and grab a screenshot in the frame before the player reappears after exiting a locker. Perhaps it has something to do with a lag in calculating what's visible to the player? A solution could be to have the player inherit visibility information from the locker on exit instead of calculating it again?

**Comment by coolcat1711** [comment]
![image](https://user-images.githubusercontent.com/3880412/53703258-e6c13800-3ddd-11e9-9746-a8247131e68c.png)

The character ends up way down here during transition into and out of the locker, would explain both the suffocation damage since the character is in space for a moment, and also why wall items flicker into existence since the angle calculation for wall items would succeed. I haven't figured out why the character ends up here yet. Maybe some interpolation problems with moving the character forcefully?
