### ISSUE TITLE
Press control + click on an object you are pulling does not cancel the pulling action B: 40

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1620]
# Description

When you are pulling something you should be able to use the control + click combo to cancel the pulling action like on byond ss13. This does not happen with current build.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Run game from steam
2. Pull an object using control + click
3. Try to stop pulling object using control + click

Bounty of 40 usd will be awarded to the contributor on a successful merge of a solution to this bug

**Comment by fomalsd** [comment]
![GIF](https://user-images.githubusercontent.com/10403536/54125606-68781d80-43fd-11e9-8396-a7253e9aac8f.gif)
can't reproduce, but noticed that left click interactions became wonky in general

**Comment by Fishfish458** [comment]
@fomalsd It seems like it might be a high ping situation since it only happens to me on the steam build, if you start pulling something it doesn't even register but it will start following you unless you push back at it. I can't get on it to make a gif right now but I was able to start pulling like 10 objects at once and the release button didn't show

**Comment by DooblyNoobly** [comment]
bug does not appear on latest steam build.
