### ISSUE TITLE
Mopping floors doesn't work for clients

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1668]
## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Join steam server
2. Grab a mop
3. Try mopping blood

**Comment by fomalsd** [comment]
Also mop has wrong inhands sprites

**Comment by chairbender** [comment]
Per @Aranclanos :
"CanUse() broke and now vending machines and others that use it wont respond to clients"

**Comment by chairbender** [comment]
@Aranclanos 

I wouldn't call it broken. The only change I made was that it no longer has the side effect of sending an interaction message to the server when it is invoked on the client side. I removed this behavior because it doesn't make sense to have a method called "CanUse" which has a quite significant and undocumented side effect of performing network communication - the method was doing too much by having this side effect.  CanUse should only be used to check if something is usable. 

Please refactor your code to send this message in a different way. 

In the meantime I will work on the other users of this method to ensure they do the same thing.

**Comment by chairbender** [comment]
We will not restore the old side-effect of CanUse. Instead I will go through the users of this method and ensure they send an interaction message when they need to rather than relying on this side effect.
