### ISSUE TITLE
From lockers, you'll always pick up breathmasks first

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1690]
# Description
When opening a locker, its possible to find guns on them. Even when mouseovering the gun and clicking on it, the object you'll find yourself picking up is the breathmask from the locker.

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1.Open an oxygen locker with a gun inside
2.Click on top of the gun to pick it up
3.Find breathmask in your hand

**Comment by fomalsd** [comment]
likely a mouseover issue. should make it respect layer order as well.
enable mouse gizmos and hover mouse over gun. if it shows oxygen mask pixels then that's the issue

**Comment by chairbender** [comment]
I believe it already is correctly sorting by sorting layer + order in layer, using SortingLayer.GetLayerValueFromID(), which I believe takes into account both of those.

I think this issue is because many sprites have an order in layer of 10. So unity arbitrarily decides which one goes first. We need to give all sprites different order in layer values.

**Comment by chairbender** [comment]
oh nvm, that method actually does ignore order in layer, need to add that to the sort
