### ISSUE TITLE
Suffocating in space with mask, oxygen tank and internals enabled

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1700]
# Description
![img](https://user-images.githubusercontent.com/10403536/55545848-a34c3900-56bd-11e9-80b6-af6027aeabc1.png)

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Start from editor, join as miner
2. Get a helmet and oxygen tank and put them on
3. Walk into space and enable internals

**Comment by fomalsd** [comment]
I think it's due to mask miner spawns with. When I throw it away and equip one from oxygen locker I have no issues

**Comment by chairbender** [comment]
This is because the mask that the player spawns with is not actually an instance of the Mask prefab, it's a uni-item which does not set its "connected to tank" flag.

Eventually I think the Job Outfit component needs to be modified to allow providing a prefab instead of a hier. For now I can set the boolean flag based on the MASKINTERNALS flag from the dmi data.
