### ISSUE TITLE
Right click: disable/hide unavailable options, dynamic rename B: 25

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#1725]
# Description

- Explore possibility of not drawing right click options if it's known that they are unavailable.
Example: ghost rightclicking item and still has a Pull option (there's a NRE in this situation by the way)

- Also renaming them depending on context would be cool ("Turn it on"/"Turn it off" instead of "Toggle")

**Comment by DooblyNoobly** [comment]
Contributor will receive a bounty of 25usd on a successful merge of a solution that satisfies the criteria above.

**Comment by Fishfish458** [comment]
doing some looking into this one

**Comment by chairbender** [comment]
Here's my suggestions from another ticket for how rightclick should work:
We also might want to think about refactoring right click as part of this (or as a second step). The actual look and feel of it is fine, but I don't know if the current approach is very scalable from a coding perspective. Any time you would want a new right click option, you would have to manually add that to the SpriteDictionary setup code in Rightclick.cs. I'm not saying it's possible to avoid having a massive list defining each possible option, but I think there might be a better way. And as an object's state changes, some interactions will become possible / not possible. Another thing I'd like to avoid with Rightclick is how the use of strings where enums or other types might be more appropriate.

At a high level, I think I might prefer an inversion of control, where each object gets to decide what its interaction menu looks like, via a component which other components can talk to.

For example, what if we have a RightclickMenu component on each object.

If you have a PushPull, when it initializes, it would tell RightclickMenu to add a menu option for pushing and pulling, and would pass a callback for what should be invoked when that option is selected.

Accordingly, each component would register itself with RightclickMenu in this way and update it to remove / add options when they become available / unavailable.

We still want to ensure a consistent ordering of the menu items, however, and we would want to ensure each menu item always uses the same image / text for the same menu option. I think we should use an approach like this: https://stackoverflow.com/a/469315/765419

Rather than Planet, it would be MenuOption, and each option would have an associated name and sprite. Furthermore, to ensure consistent ordering of menu options, there would be a static constant list which defines the ordering of each of the static MenuOption objects.

When a component wants to register a right click option, it would pass one of the static MenuOption objects as well as the callback. When it wants to de-register, it would pass the static MenuOption object to de-register. It would be required that there is only ever one instance of a specific MenuOption in a given RightclickMenu (it wouldn't make sense to have 2 "pull" options anyway).

If, in the future, we want to support having menu options which are determined at runtime (which are not one of the static MenuOption objects), it should be pretty easy to instantiate a MenuOption and assign it a name and sprite dynamically and pass that to RightclickMenu, using the object's reference to de-register it when needed.

With the approach I outlined, it would allow for inversion of control and would delegate the handling of each menu option to each component, meaning that as new components are added they can decide how they would like to influence the right click menu for only the stuff that concerns them. Each component is then only responsible for telling right click menu about its own right click menu options - leading to better separation of concern.

**Comment by chairbender** [comment]
@Fishfish458 are you still planning on working on this?

**Comment by Fishfish458** [comment]
Having computer trouble at the moment unfortunately, if anyone else wants to look at it go for it

**Comment by chairbender** [comment]
I AM still working on this. Just have been a bit busy.
