### ISSUE TITLE
New player welcome message job name inconsistency 

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#1802]
# Description
![image](https://user-images.githubusercontent.com/701959/56995108-32425900-6b77-11e9-8043-4944b7c6f0e3.png)
"Hos Edgar Butterfill has arrived at the station. Have a pleasant day! Try not to die..."

The issue is that HOS is spelled Hos.

## Category
BUG

**Comment by fomalsd** [comment]
I think it's because all jobs in `JobType` enum are initially uppercase, but then get capitalised for string representation.
JobType entries could probably be renamed so that no further capitalisation would be required
(but be careful as all editor references could be lost as a result of renaming)

This line should be tweaked to remove capitalisation:
https://github.com/unitystation/unitystation/blob/f3341d5850ad683417c6dbce50dc9c9f6defc6d1/UnityProject/Assets/Scripts/Util/SweetExtensions.cs#L138

**Comment by ghost** [comment]
I don't think that enum is the best place to put formatting for the job names because we'd need to change all code referencing it if we ever decided to change the name for a job or even change the capitalization for it or something similar.
I think it would be better to have a language/strings file that we could use to look up the right string representation.
This would also help if we ever decided to offer a non-English interface to the game.
Just a suggestion though.

**Comment by chairbender** [comment]
the display names are defined in the Occupation definitions now in #2245
