### ISSUE TITLE
Screwdriver sprite is too low in UI

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1863]
# Description
The sprite should be centred just like it is on the floor

![image](https://user-images.githubusercontent.com/4493127/57727197-c2f55a80-7688-11e9-98f1-8cc4ae4e865d.png)

![image](https://user-images.githubusercontent.com/4493127/57727201-c4268780-7688-11e9-89a9-e3d4e88f4fa8.png)

## Category
BUG

**Comment by RyanCross** [comment]
@DooblyNoobly @Jibbajabbafic Looking into this. It looks like this behavior looks is present with all the sprites, not just the screwdriver.

Prefabs for objects have had their x/y position adjusted so that they appear centered. But this doesn't work for the hand ui elements, which load the sprite directly.

**Comment by YotaXP** [comment]
Doesn't look like they have that X/Y adjustment anymore, and now display off center in the world too. Is this fix something we really want, or would it be better to just center all the sprites as they should have been to begin with?

The screwdriver below appears to be in reach, but is actually on the table.
![example](https://cdn.discordapp.com/attachments/402986688114065409/627244636276129792/unknown.png)
