### ISSUE TITLE
Replace the Mapping Wiki with this

### ISSUE THREAD

**Issue by lfricken** [unitystation/unitystation#1882]
Despite being familiar with Unity and being a full time developer, I had trouble following the mapping wiki. I made an _enhanced_ (hopefully) version. [You can view it and it's raw markdown here](https://github.com/lfricken/oni-mods/blob/master/test.md). I would be honored if the mapping wiki could be updated with it.

It contains some TODOs for either a more knowledgeable person or is waiting for future dev.

**Comment by fomalsd** [comment]
thanks! that wiki was actually really old.
I'll also add a note about wallmount gizmos that were added recently and make life easier

**Comment by fomalsd** [comment]
As for new maps, for the moment we try to stick with just one for ease of support because we add and change various systems on daily basis, and we don't have the manpower to sustain multiple maps in working state (we tried). We'll add info on how to make new maps when it becomes viable to keep and support multiple maps effort wise (like, when we add atmos pipes and disposals, and electrical system is finalized)
