### ISSUE TITLE
Can't toggle internals

### ISSUE THREAD

**Issue by Jibbajabbafic** [unitystation/unitystation#1977]
# Description

## Category
BUG

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Equip breath mask
2. Pick up oxygen tank
3. Notice the internals toggle doesn't turn solid
![image](https://user-images.githubusercontent.com/4493127/60385617-f3e7ee00-9a82-11e9-99a0-7541ee8b3e26.png)

**Comment by Schneckenhof** [comment]
Recreating issue. This is my first ever bug testing on github. I hope I'm doing this correctly: 

Step 1: Mask Equipped - No Tank - Internals toggle transparent.

![Mask Equipped - No Tank - Internals toggle transparent](https://user-images.githubusercontent.com/52392397/60415592-9c906d80-9ba9-11e9-93f9-72ba3c25f79f.PNG)

Step 2: Mask Equipped - Tank picked up in RT hand - Toggle still transparent

![Mask Equipped - Tank picked up in RT hand - Toggle still transparent](https://user-images.githubusercontent.com/52392397/60415650-b762e200-9ba9-11e9-9510-ff0f391c553c.PNG)

Step 3: Noticed Error message at bottom of the screen in Image for step 2. Expanded 
Error message and here is the screenshot.

![Expanded Error Message](https://user-images.githubusercontent.com/52392397/60415708-e2e5cc80-9ba9-11e9-8449-ea6483445da9.PNG)

Edit: I have been informed by Foma via discord that the message was in fact a "warning" and not an "error" message because error messages are apparently red.

Edit: Further testing reveals that the toggle icon remains transparent even if the mask is put on after the oxygen tank is equipped.

**Comment by Jibbajabbafic** [comment]
Thanks for confirming the bug.

**Comment by vgwiss** [comment]
Working on this!

**Comment by chairbender** [comment]
@vgwiss still on this?

**Comment by BNHeadrick** [comment]
Has this been fixed?  I'm unable to replicate this bug.  I tried it as two different characters, though I'm not sure if it matters.

**Comment by chairbender** [comment]
Seems like it. Tested locally with 2 players
