### ISSUE TITLE
Accidentally triggering Player drag to when fighting people

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2053]
# Description

so Since they drag player to thing mechanic, In combat your mouse moves a lot And of course that accidentally triggers the drag scenario instead of actually the intent you want to do this can be frustrating for Disarming and attacking since Since that blocks the attack
I did highlight this would be an issue With input

https://cdn.discordapp.com/attachments/312454684021620736/603207113325543447/Desktop_2019.07.23_-_13.49.16.28.mp4

example video

## Category
BUG

## Detailed Bug Report

Should have a bigger Dead zone so it doesn't trigger accidentally in combat

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. get Two clients
2. Try running around and spamming Disarm on On the other client
3. What the drag UI Pop-up for a tiny second Instead of hitting/Disarming

**Comment by chairbender** [comment]
I don't know if a bigger deadzone will be better. It could be confusing why drag isn't happening because it decreases the feedback indicating that a drag has started. I would suggest maybe a short timer before drag is allowed while holding down the mouse. I think there might already be one? And as soon as the timer is hit it can trigger the drag, and we can remove the deadzone.

**Comment by Bod9001** [comment]
Maybe only having drag on Help intent?
