### ISSUE TITLE
Action System B: 100

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2298]
# Description
in ss13 You can have spells and Stuff that You can select by panels on top left
This is used for magic, race abilities, item abilities, E.g Triggering Spell, Something, Jetpack settings, Stuff like that 

These are called "actions".

Add the ability to have "actions", which show up somewhere on the UI (like the top left) and can be dynamically added / removed based on various things. The actions can be clicked to trigger them, and have mouseover text explaining what they do. They might also have some sort of cooldown indicator?

For example, certain pieces of equipment come with actions when you equip them, like a helmet lamp.

Actions should be able to be dynamically added / removed regardless of WHY that happens. You can gain / lose them in various ways. Such as being a wizard.

I suggest that all actions are defined using an SO, so you can set their text, icon, and other behavior. They should have a callback that can be dynamically configured to be invoked at runtime.

Example
![image](https://user-images.githubusercontent.com/27101670/69370191-5f7e6200-0c95-11ea-8f6a-5c8d134d60b9.png)

Another example
<img width="549" alt="Screen Shot 2019-11-21 at 11 31 01 AM" src="https://user-images.githubusercontent.com/1329062/69370264-7cde0c80-0c52-11ea-88eb-64f35b883c2c.png">

**Comment by chairbender** [comment]
I'll merge mine into this

**Comment by StrawberryMoses** [comment]
In tg code these are called actions.

https://github.com/tgstation/tgstation/blob/master/code/datums/action.dm

I have an idea of how this might work, but anyone feel free to take it. I suggest key value pairs to reference actions and an object that has all information needed. A prefab can be added with the inventory background icon and an empty image for the icon overlay. Then on click can trigger if2

**Comment by chairbender** [comment]
already added this to the ticket but just as an addendum, I would suggest not doing it with dictionary key / value pairs since that's what SOs are for in Unity. It should instead be done with SOs.

Also, IF2 at the moment might not be the right thing for this as IF2 is only for things that are triggered by the predefined interaction types. It might be better to have a different system for telling the server you want to call a particular action (and the action would have some sort of unique identifier).  So maybe a dictionary of some kind would actually be needed somewhere, just so client / server can reference the same action.

Action system would probably be similar to IF2 except client would need to pass the ID of a particular action asset and the object on which the action is being invoked.

**Comment by Jibbajabbafic** [comment]
I think this should be added sooner rather than later before more items get added. It was way too much effort to add all the required stuff for an action button manually.

Some things that would have been useful:
  - An option to auto show/hide the action as soon as item is picked up or leaves certain slots
  - Handle networking for the user, so all they need to do is specify which function to run on the server/client when the button is pressed
  - Have a generic button prefab which already has the default background (background_bg_default I think) which gets populated automatically
  - Let the user assign sprites to it and provide methods to update them dynamically

**Comment by Bod9001** [comment]
ok, am Working on this

**Comment by DooblyNoobly** [comment]
#3092 failed testing on the staging server.

Buttons did not have the icons:
![image](https://user-images.githubusercontent.com/20813925/75103328-244d4f80-5645-11ea-8eba-1dab6e54224e.png)

And clicking on the action buttons breaks and throws an NRE on the client:

![image](https://user-images.githubusercontent.com/20813925/75103333-33340200-5645-11ea-968b-1daa74426a28.png)

@Bod9001 I'd advise that you test in mp before asking for pr review. You'll have to make a new PR from that branch and fix the problems listed above

**Comment by DooblyNoobly** [comment]
Other issues being reported: `If your break the chair, the broken buckle icon stays on your screen and you become invisible`

`

**Comment by Bod9001** [comment]
man, am So annoyed right now, if it didn't take like 9 days to get it reviewed Wouldn't have been Bloody broken
