### ISSUE TITLE
Refactor old mob health code and turn them into components B:35

### ISSUE THREAD

**Issue by mixxit** [unitystation/unitystation#234]

**Comment by DooblyNoobly** [comment]
edited

**Comment by DooblyNoobly** [comment]
some progress has been made with the new HealthBehaviour. This needs to be finished in 0.1.4

**Comment by DooblyNoobly** [comment]
Bounty: 35usd

Criteria:

    - Develop all new health components and depreciate old mob health code
    - Create components to handle all aspects of a players health, see suggestion below
    - Test new components in a networked environment to confirm working
    - Make sure components update the respective UI elements
    - Ensure that there are methods to reverse damage and add healing 
    - Implement a reset health method for all components for cloning
    

Contributor will receive the bounty after merge (paypal)

**Comment by DooblyNoobly** [comment]
I suggest that there be a main PlayerHealth (there may already be one?) on the parent gObj of the player prefab then to create a new child gObj to hold all of the new health components. The PlayerHealth component on the parent will reference all of the different types of health components on the child obj. This way the player prefab will remain neat and organized and we are not putting too many components on the parent.

I suggest there be a component that handles each body part. Think about what is vital to a humans health and make those components the important ones (The ones that can actually kill the player). I.E TorsoHealth(Vital) and HeadHealth(Vital) and then the other components feed overall health values into these vitals. 

Then you can finish the components for leftarm, rightarm, leftleg, rightleg and face. So if you chop off a leg then the leg component will continually remove blood from the TorsoHealth(vital) until there is no more blood left and it kills the player. To stop the blood flow another player would have to stem the vein on the leg component that is removing the overall blood stock from the TorsoHealth component. 

Have a careful think about how all the components will feed into the main vital parts and then make sure that the PlayerHealth component on the parent GameObj has ways to interact with all of the components. This way if the player has been shot by a bullet, the bullet only has to send a message to PlayerHealth that it's intention was the left leg and the PlayerHealth will delegate the damage to the leftLeg component. So the PlayerHealth component is just an accessor to report values and to call methods on the other components.

Try to come up with original ideas on how to handle all the different types of damage in a nice and simple way instead of referencing old TG health code.
