### ISSUE TITLE
Security records console's 'text input box' doesn't handle the Enter key properly

### ISSUE THREAD

**Issue by Mantle-Wanderer** [unitystation/unitystation#2347]
# Description
~~_Bod recently created a build for download on the discord server. This issue is in that build._~~
> ^ **2020/Feb/03**: This issue is still in the most recent build.

Security records 'text input' doesn't register the enter key correctly. The other hotkeys such as 't' or 'wasd' take over any time you press enter, causing you to open the chat window accidentally or start walking around whilst typing.

In the clip I type 'ttt adadad' on the first line - no issues here. Then I type 'adadadadt', then hit enter, 'adadad', then hit enter again.
[Example Clip](https://i.imgur.com/ZvdiGJ7.mp4)

**Note:**
I'm not sure we even need more than one line in the current system, but it could be useful later on.

## Detailed Bug Report
N/A

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Log into security records console and open a record.
2. Create a new line by hitting enter and start typing, the game picks up the key inputs aswell as the console.
3. Be annoyed at not being able to write fifty paragraph essays on crime and other villainous acts.

**Comment by fomalsd** [comment]
Might be some something wrong with InputFieldFocus, I recall having to nerf it significantly to avoid some exceptions and it kind of stopped working well since then

**Comment by Robotonic** [comment]
I've narrowed this down more. It has to do with the animation of the chat bubble.

Here's an example image. The top message is by repeatedly, rapidly clicking on an intercom to spam a message - I think the animaton is being interrupted and just keeps getting bigger for some reason. The bottom message is by repeatedly, but slowly clicking it so that the animation resets by the time the next click is done.
https://i.imgur.com/1TaX8s7.png
