### ISSUE TITLE
Make Roller Chairs draggable B: 50

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#2425]
# Criteria:

- Make roller chairs draggable and also play the chair rolling sfx periodically
- Change the direction of the chair so it faces the direction of dragging
- Allow players buckled to the chair to be dragged along and also face the same direction as the chair being dragged
- Ensure all of it works over multiplayer with 2 clients

Contributor will receive a bounty of 50usd on a successful merge of a solution that resolves the task request above.

**Comment by chairbender** [comment]
I think even the normal metal chairs are supposed to be draggable as well, though maybe not when someone is in them. Last I checked on tg you could drag at least empty metal chairs.

**Comment by JaytleBee** [comment]
> 
> 
> I think even the normal metal chairs are supposed to be draggable as well, though maybe not when someone is in them. Last I checked on tg you could drag at least empty metal chairs.

Just tested it on /tg/ and nope, **metal chairs can't be dragged** (however they can be picked up by dragging them onto your sprite. The same is true for (bar) stools and wooden chairs. Comfy chairs and shuttle seats can be neither picked up nor pulled. Please refer to [chair.dm](https://github.com/tgstation/tgstation/blob/6e238392bffac435bc6c2a4d614bfff0e998de24/code/game/objects/structures/beds_chairs/chair.dm) in the /tg/station github (look for the "**ANCHORED**" variable).

I think I'll try my hand at this issue.

**Comment by chairbender** [comment]
What should happen if you drag roller chairs on top of each other, or try to drag a roller chair into the same space as a metal chair?

**Comment by JaytleBee** [comment]
> I think I'll try my hand at this issue.

Due to [unforeseen circumstances](https://user-images.githubusercontent.com/7951887/70396285-b27f4580-1a07-11ea-8a83-56a2f3d818d3.gif), I won't be able to work on this anytime soon (currently don't have a good machine at my new apartment.)

> What should happen if you drag roller chairs on top of each other, or try to drag a roller chair into the same space as a metal chair?

Just tested this, two chairs (of any type, as far as I can tell) can be in the same spot (even if people are buckled to it, though you have to avoid collision by crawling into the tile).

**Comment by chairbender** [comment]
understood, thanks for providing this info

**Comment by JesterX666** [comment]
Hint:  Making roller-chair (Office chair) pullable, is really simple : you just have to add an "Object Behaviour" component to the prefab.  However, there is an issue remaining : a player buckled to the chair isn't dragged along with the chair and stay in place, which isn't acceptable.

**Comment by JesterX666** [comment]
I'll take that one.  Progress has already been made

Current state in my branch : the chair is pullable and face the player that pulls

What remains :
- The sound
- The buckled object staying on the chair
- Tests for multiplayer

**Comment by chairbender** [comment]
Additional needs for the rolling chair:

- When you push a player buckled into it, you should push them and the chair. Currently being buckled into a chair makes them immovable. Make sure to merge latest from develop since I recently changed push logic. This'll be complicated so IDK if it belongs in this ticket. @DooblyNoobly @fomalsd what do you think? (I can work on that part of it)
- When you drag the player who is buckled into the chair, you should start dragging them + the chair just as if you clicked to drag the chair. Otherwise you have to pixel hunt to click the chair under them to start dragging.

**Comment by chairbender** [comment]
Just so I don't forget since I looked at it...For the pushing part of it, on clientside PlayerSync.DoProcess needs to be updated, probably only in PredictiveBumpInteract where it calls TryPredictivePush and CmdValidatePush. We have clientside prediction for pushing and currently if client sees that there's a buckled player they don't think they can push. The logic needs to be expanded to check if the player is buckled into a pushable chair. And the predictive push needs to push the player and the chair.

On server side, PlayerSync.NextStateServer is the main area where this is checked, specifically when it hits the BumpInteract, which eventually reaches the InteractPushable method call in TryInteract. InteractPushable would need to allow pushing players buckled into pushable chairs rather than assuming all buckled players aren't pushable. And the actual push needs to push the player and the chair.

**Comment by JesterX666** [comment]
Push and pulling the player on the chair has been corrected (Pull Request upcoming after a few tests)

However, I have a problem with Rendering Occupant+ Chair.  Sending two messages causes too much of a lag, Sending a single message and drawing both the occupant and the chair on client side also causes a similar lag.

There is only two way to solve it imho :

- Synchronizing all the move frame-by-frame for the two sprites (very hard and prone to not work very well)
or
- Compositing the two objects as a single sprite (easier I think)

Feel free to throw on other ideas.

**Comment by chairbender** [comment]
weird, I wouldn't have expected it to cause lag. I'm curious what the lag looks like, if you can upload a gif it would be helpful, otherwise I can look at it when I get the chance.

My guess is if it still doesn't look like they move together or they move in a stuttering fashion, there is an issue where client prediction is not being done on both objects.

Compositing the two objects is definitely an interesting idea, but sounds very scary thinking about how everything has been relying on a particular structure for our objects so far, this has never been done. Plus it might really screw with networking - Mirror does not allow having nested objects with a network identity, the "composite" object would need to have its own network identity separate from the objects it contained. I wouldn't suggest it. I know our movement system has the ability to make this look smooth, just a matter of figuring out what it needs.

**Comment by JesterX666** [comment]
I should have been more precise but your guess was right : the two objects still dont move together.

What i'm talking about by compositing is the following : 

Creating a single sprite out of two sprite, that allows to move a single pixel perfect sprite.

Or maybe you can take a look at it and tell me what it needs after we merge it with the upstream?

**Comment by chairbender** [comment]
Yeah compositing would create a lot of issues. We should support objects moving together without needing to combine them in the hierarchy. I'll take a look at this in a bit

**Comment by chairbender** [comment]
Another issue I noticed even with the latest PR - when you strap someone into a chair and push them into space, the chair flies off without them but they are still marked as being buckled to it.
Furthermore I expect there would be issues if the chair / player were moved due to other external factors, such as newtonian impulse (shooting a gun in space) or wind.

We basically need support in the movement system to "weld" objects together so that no matter how they are moved, they will both move together. Might need to slightly rework the CustomNetTransform changes in this PR to support this but the rest of the code should be fine.

**Comment by chairbender** [comment]
Alright @JesterX666 I'm figuring out how to weld things together. The complication I forgot about is, players don't have a CNT - networking movement logic is handled in PlayerSync for players and CustomNetTransform for everything else, and they both have been using IPushable to help encapsulate common logic so I'm planning for the welding logic to go there. Don't worry about stepping on my toes for the changes you're working on.

**Comment by chairbender** [comment]
Eventually we also want to be able to let you trigger newtonian impulse movement while in a rolling chair - spraying extinguisher or shooting a gun or throwing something for example - even when you're on a station and not in space. As I work on this I'll look into the feasibility of that, if it's too big of an effort I'll make a separate ticket. Might not be.
