### ISSUE TITLE
Oxygen tank doesn't equip in suit storage by pressing equip button

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#2563]
# Oxygen tank doesn't equip in suit storage by pressing equip button

## Description
Oxygen tanks doesn't equip in suit storage by pressing equip button.  The bug only happens when other hand is free. Oxygen tanks don't have suit storage trait which is not implemented yet (see **BestSlotForTrait** and **ItemTypeToTraitMapping**). 

### Steps to Reproduce
1.  Take oxygen tank in active hand
2.  Press E button
3.  Oxygen tank doesn't move to suit storage

**Comment by chairbender** [comment]
Additionally, BreathMask does not auto equip into the mask slot.

This can be fixed probably without any coding! You'll need to edit some scriptable object assets:

- The HumanCapacity needs to be modified so that the suit storage slot accepts the OxygenTank.
- The BestSlotForTrait asset needs to be modified so that breath mask will equip to mask slot if it's available and oxygen tank will equip to suit storage slot if available
- BreathMask and OxygenTank prefabs might need additional traits (in their ItemAttributes component) to allow the above assets to appropriately filter them

You can reference inventory system documentation here: https://unitystation.github.io/unitystation/development/Inventory-System/

**Comment by fomalsd** [comment]
breath mask one is especially annoying, I'd love to see this fixed before 0.4
