### ISSUE TITLE
Some tiles can become with a Z position of -1

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2610]
Some tiles sometimes get negative values (-1) as a Z coordinate.  That used to create NaN in atmos but it's been protected now.

@fomalsd started to correct those but it needs to be tested and integrated + see if there is more way to do this.

In @fomalsd  branch:
https://github.com/fomalsd/unitystation/commit/9d8d838ad448a9fc262e455b20e13d99a58da773#diff-2207370319bc3583c2cb28e5040804e9L41

Steps to reproduce the bug or behaviour:  

1.  Inspect tiles positions
2.  Crash a Matrix into the station
3.  You can perhaps log when this happens

**Comment by fomalsd** [comment]
It's easy – that's because some effect tiles like glass cracks exist at Z=-1, and it's normal.
Then, when tiles on each layer get destroyed, there's an attempt to refresh atmos (`subsystemManager.UpdateAt`) for given Vector3Int position, and it triggers creation of MetaDataNode at this position if it doesn't exist:
https://github.com/unitystation/unitystation/blob/ac74414c50782032b41f93e8d40d7fc5e8d99582/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/AtmosSystem.cs#L21
So my fix is quite sufficient.
I don't think it's worth a bounty since it's already fixed in my branch.

There are waay more complex issues with ensuring MetaDataNode uniqueness per world tile anyway (#2291)
