### ISSUE TITLE
Some of the audio is getting compressed Volume wise

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#2621]
It's most noticeable on the, Announcement about hostile activity

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Listen to announcement about hostile activity
2.  Observe Distortion

**Comment by chairbender** [comment]
It's intentional that audio is getting compressed, see the messages in soundfx channel:
Doobly Yesterday at 11:24 PM
trying to fit in some sound mixing with my next PR
I put a compressor in and I'm trying to get the majority of sounds playing in a 12db range
so just adjusting other volumes here and there
If you don't like the way something sounds feel free to sneak in some updates
also if you want to tinker with the compressor it is on the MainMixer. I've removed some audiosources from the mixer on purpose (because their sound clips are already well mixed and I want to force them more into the background)

**Comment by PerfectTangent** [comment]
this doesn't seem to be relevant anymore.
