### ISSUE TITLE
Better Comms Shortcut Keys for Radio / Local

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2654]
## Description

I'm not quite sure what the best behavior would be for this (not familiar with what people are used to from BYOND), but it would be nice to be able to quickly type a local message by hitting a key (like t) regardless of whether you had previously selected for chat or radio channels. Currently if you press t it keeps radio channels selected and sends a radio message.

**Comment by Fishfish458** [comment]
adding onto this i'm sure quite a few people would be interested in the chat shortcuts as they were even as an option.
 by pressing enter and prefacing your message with a radio channel prefix, you'd speak on that channel, otherwise you'd speak in local chat:
"i am speakin in local chat"
"; I am speaking on public radio"
":s I am speaking on security radio"
so forth on https://tgstation13.org/wiki/Radio_channels

**Comment by Jibbajabbafic** [comment]
Currently 'T' opens chat with the previous channels, 'Y' opens common radio chat and 'U' opens OOC.
I think changing 'T' to always do local chat would probably be better, alongside those chat modifiers that you mentioned.
