### ISSUE TITLE
Make shuttle to not use the same power-grid as the station B: 30

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2662]
Actually, if the station lacks power, the shuttles lights are off.

1.  Lose station power (wait for plasma to be burnt or turn off power)
2.  Go inside a shuttle
3.  No lights!

That also happen if you're flying a shuttle and power stops in the station at a distance.

**Comment by chairbender** [comment]
I think there already is a "self powered" flag that lives on the light switch or light bar or APC, it may not be checked on some of the shuttles.

**Comment by DooblyNoobly** [comment]
oh just read about the self powered flag. Will reduce bounty to 30

**Comment by krille90** [comment]
Looks like all light switches in the shuttles are already on self-powered.
Was that maybe changed recently?

**Comment by JesterX666** [comment]
I guess it depends on the shuttle, some do, some don't :

![image](https://user-images.githubusercontent.com/32009105/73324407-ccbfed80-4218-11ea-8826-ffb4b97dde0f.png)

**Comment by chairbender** [comment]
I think this is probably due to #2485 

EDIT: ..I mean it's due to that if what's shown above is that they are mapped as self powered but the lights aren't being properly hooked up to those switches when the round starts and the lights / switches all initialize. Which is what I think is happening above.
