### ISSUE TITLE
Playing the game on fullscreen with AMD's "Virtual Super resolution" causes the game to have low FPS

### ISSUE THREAD

**Issue by RealPlanet** [unitystation/unitystation#2704]
VSR allows you to select higher resolutions which will then be downscaled to fit the monitor, I believe Unitystation is selecting the highest possible when going fullscreen causing low FPS. Disabling it removes any trace of the problem.

Steps to Reproduce
Just turn on, VSR while playing on fullscreen, going to window mode fixes the problem.

**Comment by daalta** [comment]
Did you enter fullscreen using ALT+Enter or using the fullscreen option in the menu?

We could definitely fix this by introducing a resolution option. Right now the game tries to detect your native resolution automatically.

**Comment by RealPlanet** [comment]
Sorry forgot to mention it here, yes this is using the fullscreen option in the settings.

**Comment by daalta** [comment]
@RealPlanet Thanks for the info!

Here are some ways we could solve this problem:

- Change how fullscreen resolution is determined, or
- Change fullscreen to windowed borderless fullscreen (in player settings), or
- Add resolution settings to the options menu

As a workaround you could play the game in maximized windowed mode, at least for now.

**Comment by daalta** [comment]
~~It would be helpful if some other users could report their experiences with playing Unitystation on a high resolution. Then we'd know if this is specific to AMD's downscaling or if this is a more general issue.~~

Yep, turned out to be a general issue with the game. Maybe there's something we can do to improve performance on higher resolutions, like decreasing the rendering scale of the station while keeping the UI at high resolution.

**Comment by PerfectTangent** [comment]
This looks to be just general performance issues rather than an issue specifically with AMD's downscaling. Closing.
