### ISSUE TITLE
Connected plasma tank leaks into the atmos

### ISSUE THREAD

**Issue by JesterX666** [unitystation/unitystation#2709]
Even if a plasma tank is placed on a connector and secured with a wrench, it's content leaks into the ambiant air.

Please enter the steps to reproduce the bug or behaviour:  
1.  Drag a plasma tank into the mining shuttle.
2.  Place it on the connector.
3.  Secure it with the wrench.
4.  Turn it on.
5.  Observe the athmospheric values, plasma and pressure are climbing.

Expected behaviour:  a connected plasma tank should not leak.

**Comment by chairbender** [comment]
Also be aware that currently there's no requirement to open the release valve when attached to connector in order to provide fuel for the shuttle.

**Comment by Mantle-Wanderer** [comment]
When you say turn it on, do you mean you're opening the release valve on the canister? It's a common mistake people make on BYOND SS13 too, but once a canister is wrenched onto a connector it's already sharing its contents into the pipe. No release valve needed.

The way it's set up can be useful because on BYOND you can have a canister connected to some pipes, put a tank inside of the canister, and then pressurise the tank using the release valve without having to disconnect it from the pipes.

I see this happen all the time on SS13, so if there's any way of making it more obvious that'd be great.

**Comment by JesterX666** [comment]
Oops, yes, I was opening the release valve.  I tought I had to do that to fuel the shuttle.

I'm closing this issue.  But I agree that it should be more obvious.  Maybe one day.  That's not urgent.
