### ISSUE TITLE
Download progress bar dissapears in the Hub when pushing the refresh button

### ISSUE THREAD

**Issue by MNarath1** [unitystation/unitystation#2725]
When you push the refresh button in the hub while you are downloading a build then the download bar disappears but the download still goes on if you then click the download button again the download bar will start from 0 trough the old download seems to still go on.

**Comment by corp-0** [comment]
![GIF 27-08-2020 17-20-48](https://user-images.githubusercontent.com/43683714/91496187-b00c9680-e889-11ea-9a73-b7470e6dc1b5.gif)
This doesn't happen anymore. I mean the bar goes back to 0 but it quickly returns to its current position and it goes back to 0 randomly anyways without pushing the refresh button. Closing this since the problem described isn't what happens anymore.
