### ISSUE TITLE
Chat messages cause lag B: 120

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2748]
## Description
Some players have observed that their client lags when a new chat message appears. Doesn't seem to effect everyone.

**Comment by chairbender** [comment]
Putting in 0.4 because it causes client-side lag which affects playability

**Comment by daalta** [comment]
Hmm... Are the clients experiencing framerate drops or actual network lag?

If we have framerate issues then the issue might be related to chat processing / parsing, or maybe the rendering of chat.

If it's a networking issue things might be harder to diagnose.

**Comment by chairbender** [comment]
Marking as needs reproduction, I'm not sure who is able to reproduce this, probably @Bod9001 who reported it

**Comment by DooblyNoobly** [comment]
I think this was reported when we had a tonne of server NRE's it was most likely due to that. Lets close it and reopen if its reported again

**Comment by daalta** [comment]
I'm experiencing this issue in our most recent test.

We has 15-25 players. Every time a chat or combat message appeared the game seemed to freeze for some amount of time.

**Comment by DooblyNoobly** [comment]
basically instead of instantiating new chat entries we should make a pool for them (don't use pool manager just create a real basic one for the chat feed) and start with a cached amount of entries already pre-populated in the pool so we are not instantiating and destroying so much (which is leading to the garbage collection pauses - lag)

**Comment by fomalsd** [comment]
my fix will involve Outpost scene change, be aware
