### ISSUE TITLE
Escape shuttle reaches ludicrous speed

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2844]
## Description

Escape shuttle accelerates faster and faster, which is funny, but it eventually reaches a ludicrous speed and never actually triggers the round end.

**Comment by Mantle-Wanderer** [comment]
This will make the server crash until manually restarted.
![Escape Shuttle Floating Point #1](https://user-images.githubusercontent.com/12883734/73618330-e600d980-461e-11ea-88f4-86a8264e2bdc.png)
![Escape Shuttle Floating Point #2](https://user-images.githubusercontent.com/12883734/73618565-7a1f7080-4620-11ea-8a01-a52644e00371.png)

Floating point rounding errors become extreme, shuttle starts vibrating left-to-right increasingly erratically due to this, space disappears, and everything goes black until your game stops responding and the server drops off the hub entirely.

https://youtu.be/ygE01sOhzz0?t=72

**Comment by chairbender** [comment]
fixed in #2850
