### ISSUE TITLE
Assign unique sorting indexes to items

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#2864]
When hovering a bunch of items you expect to pick up item at the top of the pile.
Selection outline reveals that it is often not the case and instead you pick up the bottom one...
![Scr 2020-02-03 at 22 58 12 2020-02-03 23_01_28](https://user-images.githubusercontent.com/10403536/73686511-2cb30a00-46d9-11ea-922b-57d3266c773b.gif)

**Comment by chairbender** [comment]
the "what did I click on" logic should already respects ALL drawing sorting logic. This is most likely caused by items having ties - being in the same sorting layer and having the same sorting index.

IMO we need something that will automatically assign unique sorting indexes to all sprite renderers in all prefabs. 

EDIT: More details on sorting here: https://docs.unity3d.com/Manual/2DSorting.html#tiebreak

I think this is a Tiebreak situation. Though it's possible the "what did I click" logic is missing out some aspect of sorting that we already have.

**Comment by fomalsd** [comment]
Reopening under a different name

**Comment by NoooneyDude** [comment]
Similar to #2439.
