### ISSUE TITLE
Shuttle lags back when crashing in the station

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#2880]
### Detailed Bug Report
* happend on GER server
* after crashing a shuttle into the station, the shuttle got partially stuck
* looks like it jumps back several times

![image](https://user-images.githubusercontent.com/7312905/73753341-d4284f00-4762-11ea-8f0d-7bc9702a94fc.png)

![image](https://user-images.githubusercontent.com/7312905/73753450-046fed80-4763-11ea-8155-e5ac5dab9300.png)

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Be on server
2.  crash shuttle into station
3.  see how it jumps back like it's lagging

**Comment by MaxIsJoe** [comment]
I'm removing the headless tag from this because this can be experienced on local host as well in both the client and editor.

This issue is very subtle on self-hosted games due to the lack of network lag, but if you push shuttles to their highest speed you can notice the faintest hint of rubberbanding occasionally and is even more noticeable if you break the current speed limit of shuttles.
