### ISSUE TITLE
Asteroids can spawn in flight path of escape shuttle

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2978]
## Description

And there's no way to really remove them. Add better logic to the asteroid position randomization to ensure it won't spawn in the way of the shuttle.

**Comment by The-Scout** [comment]
Il miss this bug. would be a interesting traitor item, spawns asteroids randomly with a highish chance of being infront of the shuttle

**Comment by ghost** [comment]
> Il miss this bug. would be a interesting traitor item, spawns asteroids randomly with a highish chance of being infront of the shuttle

As traitor you can already cause shenanigans by positioning shuttles in the emergency shuttle's flight path. It's fun.

Honestly why not make front walls of the emergency shuttle a special type that can't get destroyed during matrix collisions? It's currently trivial to kill 30 people by just taking the miner shuttle and placing it in the shuttle's flight path. And it'd be quite aesthetic to see the shuttle plowing through small shuttles and asteroids alike...

**Comment by The-Scout** [comment]
i like gardenBanters solution better.

**Comment by Misterixmax** [comment]
Escape shuttle and cargo shuttle just need to arrive from warp and fly in warp. That's all. There is no other possible ways. People may damage them during the round that's why. For cargo shuttle we need implement auto repair if shuttle being damage on centcomm and take points from cargonia if that happens.

**Comment by daPotato** [comment]
Personal opinion, I find stuff like the cargo shuttle ramming into mining shuttles to be absolutely hilarious and can be a great opportunity for sabotage, like what gardenBanter said, but the asteroid thing is certainly something that shouldn't happen since its entirely uncontrollable. Just having the ships warp in and out isn't at all appealing.

Writing this at 2 AM, fuck grammatical sensibility.
