### ISSUE TITLE
Players in lockers stop existing after the locker is destroyed

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#3001]
## Description

[Dragonbrother7](https://www.reddit.com/user/Dragonbrother7) reported [here](https://www.reddit.com/r/unitystation/comments/f1az0b/found_a_bug/) a bug related to players in lockers.

If a locker is destroyed while a player is inside the player ceases to exist and does not die. They are still able to talk.

I have not verified this issue myself, so it'll need to be reproduced.

### (Suggested) Steps to Reproduce
1.  Enter a locker and lock yourself in
2.  Have the locker destroyed (the user reported that the issue occured when crashing with a shuttle)
3.  Observe the player's state. Are they dead? Can they move?

**Comment by ghost** [comment]
It did happen to me, in game a few days ago. 

It occured in sec. 
I couldn't move at all but i could speak.

**Comment by fomalsd** [comment]
did you notice if other locker contents (items) also disappeared when locker was destroyed?

**Comment by fomalsd** [comment]
Oh, did your camera and health UI freeze as well? Еhis happens when player is returned into pool (due to ObjectTile removal) while getting destroyed by shuttle. This is not supposed to happen because living damage is applied first, but probably being in a locker changes something...
https://github.com/unitystation/unitystation/blob/0b1d6b1c209b57d390c1761a80063ef31614b566/UnityProject/Assets/Scripts/Managers/MatrixManager/MatrixManager.Collisions.cs#L359-L369

**Comment by ghost** [comment]
I don't remember my camera freezing, although i will try reproducing the bug again.
