### ISSUE TITLE
Harm intent on department battery does not attack it

### ISSUE THREAD

**Issue by pridit** [unitystation/unitystation#3104]
# Issue Template

## Description
When using the harm intent to melee attack a department battery it toggles the action instead of attacking it.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Select ``Harm`` intent.
2.  Click on ``Department Battery`` with empty or full hands on the next tile.
3.  Watch as you toggle its active state instead of attacking it.

**Comment by Tjarr737** [comment]
This seems to be a rather widespread bug (most, if not all machines).
Many objects with both a meleeable-component and some other interactive component have the meleeable-component above the other interactive component.
If the interactive component does not check for harm intent, it will be triggered and the meleeable-component never reached.

This could be fixed by making all relevant interactions checked (no interaction when the intent is to harm) or dragging the meleeable-component below them. 
Alternatively, meleeable could get some sort of extra priority above all other interactions, which would remove the risk of this repeating, but may have implications which are too far-reaching.

I am somewhat unsure on what do do of these options and would like some comments on them.
