### ISSUE TITLE
The Door opening beep is incredibly annoying.

### ISSUE THREAD

**Issue by NeotericNoble** [unitystation/unitystation#3134]
## Description
The station at the moment is so small, and thus you are hearing a beep every three seconds. 

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  Open a door.
2.  Hear a beep.

Alternatively.

1. Do nothing at all.
2. Hear a beep.

**Comment by daalta** [comment]
I agree that this might be an issue with the current station at higher player counts. Perhaps we could lower the volume?

Though I *personally* don't find them *incredibly* annoying, and think they're actually kind of useful?😬

**Comment by AlphaBuffalo** [comment]
This might solve itself with larger maps

**Comment by Ninjaboi8175** [comment]
It might be worth making a client-side volume mixer where you can adjust the volume of certain commonly complained sounds. I do think that a larger map might help but if it's the door sounds that's annoying then it won't change much as players tend to cluster together. Not to mention larger maps on higher population servers would still have the same issue.

In my case I don't really mind it. Since the doors also have the door sliding sound alongside the beep, it might be okay to allow users to opt-out of hearing the beep as they can still hear the door opening and shutting. Assuming those are two separate sound files. If they aren't then maybe we can have two versions where one omits the beep and we swap them when someone opts out of it.

**Comment by PerfectTangent** [comment]
This no longer appears to be a relevant issue what with multiple dramatically larger maps in rotation, now.
