### ISSUE TITLE
feature: stamina system for making walking great again or: why a deceleration of the gameplay would be a good thing

### ISSUE THREAD

**Issue by Dropgunner** [unitystation/unitystation#3220]
### tl:dr  Limiting running by introducing a stamina system. This would let to improved gameplay 

 I am making the argument that _**constant running has a negative effect on gameplay.**_ 

Unitystation is in itself a fast game. The player has to constantly keep an eye on his environment, read the chat and manage his own tasks. All of this requires high levels of attention

Every factor that speeds up the game contributes to the fact that players cannot enjoy the game because they cannot follow the flow of the game.

They take advantage of the pace of the game to gain an attention advantage over other players. 
Examples are

-  instant plasma flooding, 
-  nukerushes 
- PvP with macros where players have already saved their key combinations in muscle memory and third party tools

 The result are frustrated players who find a destroyed station after 5 minutes. 
I therefore suggest that running in the game should be limited to short or medium sprints. Positive outcomes would be: 

- **Rush strategies will be reduced**, as players will not be able to move as fast as before to execute certain strategies successfully.
- **Players have time to react**, are not overwhelmed by situations, and PVP is less likely to become Clickfest
- **Slower players also mean better latency and less rubber banding.**
- If sprinting was a limited resource, such as through an endurance system, **more tactical battles** would be possible.

**Comment by linked7** [comment]
do you think you could write in paragraphs

**Comment by Dropgunner** [comment]
> do you think you could write in paragraphs

Better?^^

**Comment by Raptorizer** [comment]
As long as stamina is kept too running and only depletes/lowers via running, obesity,  traits,  and leg issues. I am heavily against seeing stamina weaponry that ends up being the go to for combat.

**Comment by linked7** [comment]
moving slow isn't fun

**Comment by voidel** [comment]
Current speeds are pretty comparable to a low/no lag SS13 server.

**Comment by corp-0** [comment]
> Current speeds are pretty comparable to a low/no lag SS13 server.

But you can't deny that we're used to run speed on byond because it most of  the time felt like normal walking speed.

**Comment by daalta** [comment]
You make some very good points.

As someone who's relatively new to the game I've also felt that things happen an a very quick pace - compared to the text-based nature of the game. I wouldn't mind if players weren't *constantly* zipping around.

Stamina also seems very thematic. And funny. I'd love to see players wheeze and collapse on the floor because they've been running nonstop.

Though I feel like a more basic system that forces players to walk after running for X minutes might suffice. So many ways to implement this! Really fun idea 👍

**Comment by NeotericNoble** [comment]
This is supposed to be a faithful recreation of SS13. Now is not the time for balance or design changes. Now is the time for feature parity. Nothing more, nothing less.

**Comment by daalta** [comment]
@NeotericNoble I agree with you in general. Unitystation **is** supposed to be a remake of Unitystation, and we have to be careful when thinking about new features.

Tgstation actually has stamina damage, which is not exhausted by running though. But some Goonstation editions of the game have a stamina system:

> Also located there is the stamina indicator, which governs your endurance. By default, your stamina total is 200 and regenerates at a rate of 10 per tick - click on the indicator to find out about your current status. Every offensive or defensive combat interaction with a player (like attacking or disarming them) will drain stamina. You may also use stamina to move significantly faster by holding the SHIFT key. Once your stamina reaches less than 0 you will be unable to talk, stand up or even interact with any items. Your odds in combat can be improved with a variety of drugs and by wearing protective clothing. 

So to me the idea of a stamina system in Unitystation doesn't seem unfaithful to Space Station 13.

If the idea's fun and makes the game better, then why not implement it?

**Comment by juanototo2** [comment]
First. The general consensus among the Unitystation dev team is to create a clone of 2014-2016 era TGstation, pre-citrus. Removing running would fundamentally be at odds with this. TG during those days was fundamentally designed around stun based combat and dodging, with OHKOs and surprise attacks expected - but after the prepped tools are used and both don't die instantly, it turns into a game of dodging correctly and good movement. This is GOOD, as it introduces skill into a combat system that would normally be devoid of it, while not completely devaluing prep and friends and making antags still a threat to even the most well prepared if they get caught with their pants down or slip on lube. Removing speed would heavily tip the balance towards those tools, like what happened with chloral hydrate, parasting, and parapen c4, and would turn conflict resolution into a game of who can enforce their personal space better, who can bring more metafriends, or who can shove more stun reduction down their throat. This is BAD for the GAME, as I'm sure you'll understand.

**Comment by Dropgunner** [comment]
Nobody ever demanded or wrote to remove running in the game. The idea was to make running a resource that can be used tactically and not constantly.  I just checked out SS13 yesterday and found out that it has stuff like janicarts which could be implemented as a general way for transportation in unitystation if someone wants to "run" all the time.

**Comment by juanototo2** [comment]
Keeping old TG balance involving run-based combat requires the ability to jump from sitting at a table playing poker, talking to the HoP or HoS from the other side of his desk, or just roleplaying in the roleplaying game to full yakety sax mode at the drop of a hat. Why? You would have to have a bind to toggle run ready on something like Mouse4 in order to have the same capacity to take advantage of a target's incompetence at murdering you. When you can get two-hit-critted with a revolver or tased and toolboxed instantly without recourse except for that wonderful thing so many things have been nerfed for preventing, ;HELP MAINT, even a two-second difference could be vital to prevent you from being disabled from the ability to play the video game for up to *TWO HOURS*. If you don't think one mouse click would turn the game into a Mexican standoff with stunprods, autism and 2016 era disarmspam simulator, then you underestimate our playerbase. And that's not without the removal of running making half of the POINT of the Janitor fucking irrelevant - or the fact that having Cerestation levels of movement time is SO BAD that people suicided en masse at the HOP line and rushed the shuttle to get them off that station, even after telepads and transit tubes were added to lessen the pain!

**Comment by daalta** [comment]
@juanototo2
Just to reiterate what @Dropgunner said... This isn't about **removing** running, but making ~~running~~ stamina a resource that replenishes over time.

If we make stamina very generous then it would only affect players who zip around the station non-stop. Combat would be completely unaffected (unless the player just ran a marathon).

If we make stamina a more limited resource, then... "full yakety sax mode" would still be possible, just not forever.

Has a stamina system ever been experimented with? It seems like a touchy topic.

**Comment by juanototo2** [comment]
The main problems with a whole-hog no-compromises movement stamina system are twofold: Effective map scale, and no automatic toggling in combat. The effective map scale problem is essentially seen as Cerestation's "walk a marathon and back to leave your office for pizza or a cargo order" problem that turned at least 5% of the round length in even a moderately moving job like our janitor from earlier into just transit, which the playerbase wasn't pleased with, but effective on even smaller maps like Box and Meta. If you turn running into something that has about the same recharge time as the Half Life episodes' flashlights but with a small running-energy buffer, and if the difference between runspeed and walkspeed is significant enough to warrant it, you will see the powergamers you wanted to stop "leapfrogging" through the halls - running forward until it runs out, placing self in locker with homemade weapon drawn in case anyone hostile opens it, waiting the time for running to stop ticking over, and then emerging with Sprint enabled. This means that at no point during their transit would they be both vulnerable and slow at the same time, causing the same problem of being unable to interact with people in the halls because everyone just runs away. And your movement stamina won't stop plasmarush strategies or similar unless you set everyone's stamina to 0 at the start of a round, which absolutely nobody involved will like. And there's the problem of people just mass-producing hyperzine or whatever to completely sidestep the problem.

Automatic toggling in combat is something I briefly touched on before, but I need to talk about it here. SS13 combat is fast, it is unforgiving, it relies on equipment and prep, and it consists of two halves - initiation and dueling. Initiation is what you've been hearing from me this whole time - the colloquial over-the-table wordless magdump, the sleepy pen to the face with complimentary e-bow, the pre-nerf zombie powder and the parapen c4 of yore. Movement stamina will fuck both of these over in major ways unless it is neutered. Initiation will force you to press a hotkey or click the WALK button to RUN upon surviving your opponent's initial volley, if you want any chance of success, which will mean that not only does it mean a potential noob-trap, but it would incentivize macros and said mouse4 movement intent bind, devaluing skill and adding value to overpriced gaming mice. 
And as for how it would fuck over long term combat, without a stupidly long buffer - if you get into a fight with someone, and it lasts for long enough, and you have less friends and or hyperzine than the other guy, you AUTOMATICALLY LOSE. No chance for skill, no chance for prep, no chance for lone heroes or competent assistants, just metagangs that can cover each other while their stamina regenerates and powergamers with enough hyperzine to fill a small pool winning the whole time.
