### ISSUE TITLE
Feature: Hacking ideas and improvements B: 69

### ISSUE THREAD

**Issue by The-Scout** [unitystation/unitystation#3315]
/u/HeatLiquid posted this mock up of a hacking ui. https://i.imgur.com/9Ly0tIM.png
"It would be great if the hacking system allowed to swap the connected wires."

I think this should be worked on being implemented, but sadly don't have the coding knowledge to do it myself so an issue seems most worthwhile.

Some wire crossing ideas.

High Voltage Ground linked to id scan, shocks person trying to open the door if they have a valid or invalid id.
High Voltage Ground linked to bolt wire, when bolts are down, shocks people.
Safety wire linked to bolt wire, crushes people like a safety wire cutting, but bolts down after.
Bolt lights wire linked to power, bolt lights always on, even if door is not bolted.
Open linked to id scan enables emergency access?
Goes without saying wireless transmitter taped onto interface is the best thing ever.

Any other ideas?

**Comment by Fortune117** [comment]
I've begun work on this, will try to post updates as I make progress.

**Comment by Fortune117** [comment]
Hacking is now working and networked, uses a node based system rather than the original /tg/ version of hacking.

https://cdn.discordapp.com/attachments/702433902991638559/703191533137952828/unknown.png

For example, this configuration opens the door only if you have the wrong ID card.

Still have to add power cables, bolting, and a few other wires but for the most part it should be able to mimic everything the old system could do, as well as allow more custom hacks.
