### ISSUE TITLE
Different character races to choose from!

### ISSUE THREAD

**Issue by Evan-R-Rogers** [unitystation/unitystation#3331]
_"Variety is the spice of life"_
                         - Ghandi

In SS13 cannon, there exist many races from slime people, plant people, to others entirely composed of plasma that set aflame when exposed to oxygen. A few that the community have wanted are detailed below, totally not biased.

**Sheeples**
- Sheeples are people...but sheep. Their sprites are about half the size of the average human, they're covered in wool (Considered a quality textile among several factions), and are rather easy to harm. Overall 7/10 squishy and good for canon-fodder.
Traits:
       - Take twice the brute AND burn damage that humans do.
       - Have a lisp that makes them 'baaAh' like sheep  ("ThaaaAAats baAad!").
       - Able to be sheered for wool.
       - Drop twice the meat that humans drop on being gibbed. For when you're hungry.
       - Technically not human. Go nuts, AI.

**Lizard-people**
- Basically the same as sheeples except they're lizards, not sheep. They're rather scary looking, dry, usually xenophobic.
Traits:
        - Their unarmed attacks (punching) do a bit more brute damage due to having claws.
        - They speak with a 'snek' lisp   ("Sssssneaky...").
        - Drops a lizard hide that can be sewn into a neat trenchcoat or boots!
        - Looks ssSssnazzy in a cowboy hat!
        - Not able to eat cooked food.
        - Not a human.

**Plasma-men**
- Despite having 'men' in their name, they don't have a sex due to being a, well, cloud of concentrated plasma inside a hardsuit.
Traits:
        - Catches on fire when exposed to oxygen. Toasty!
        - Spawns wearing a specialized hardsuit.
        - No need to eat, drink, sleep, or probably defecate.
        - You probably shouldn't shoot them.
        - Somewhat slower than the average human due to the weight of their hard-suit
        - Human? Not anymore at least.

**Vermen**  _get it?_
- Big teeth, fleas, and bald tails are a few acronyms to describe the 'Vermen', a sentient race of anthro-rat people that are more or less akin to the Skaven (Please no DCMA). They're vile, disgusting creatures that would rather steal than barter, a perfect race for shitters to be shitters.
Traits:
         - Less afflicted from viruses/diseases than their more human counterparts.
         - Runs about .5 times faster than the average human.
         - Needs to eat more often, yet able to consume trash and rotten foods.
         - Able to see slightly better than humans in darkness, only slightly.
         - Have 3/4's the health compared to humans
         - Are they human? No, they're born from test-tubes.

**Comment by Buldinn** [comment]
Hello! My name is Buldinn and I'm the one begging for the Sheeple race haha. I want to say first and foremost that if a majority of the station hates the sheeple when they come out Im okay with their removal. I will not hold the station hostage and I am more than willing to talk to the community to help balance them or change their lore if needed....!

I was wondering if it would balanced or okay if you hugged the sheeple (on a cooldown) you could get healed for just a tiny tiny tiny bit of brute damage cus they're precious and cute lol.... And also if they could hide inside small things like Fire Extinguisher Cabinets

I'd really like it if Nanotrasen considered the sheeple "property" in a way so that it wasn't just okay to kill them but AI wouldn't take the same steps to protect sheep like they would a human, because in AI's head it's just "property".

In my canon (willing to be open for change) they dont understand the concept of money and can follow instructions to the letter, even if they can't comprehend a thing they're doing. Because of their ability to follow instructions and inability to understand money, Nanotrasen "rescued" them from their very hostile planet and now the sheeple are completely loyal to true Nanotrasen authority.

In their base society any kind of leadership is rare, so they follow anyone who isnt doing the same thing everyone else is so when NT came in they instantly pledged loyalty to anyone in a Nanotrasen uniform, at least they can understand rank and things like "murder bad", they know that if they get in trouble bad things could happen and the sheeple are very afraid of bad things.

**Comment by Evan-R-Rogers** [comment]
_help me_

**Comment by MrBobCool** [comment]
> -Not able to eat cooked food.

Lizard-men (based off of most ss13 servers) usually don't eat plant based foods. Eating a cooked steak or pack beef jerky is fine . Eating something like a apple will taste bad to them and can cause nausia. _Yes I'm a lizard main._

**Comment by ReiderJack** [comment]
Shearing sheep-people to leave them naked and ashamed. 
Cargo techs hunting sheep people for wool with scissors all over the station.
 QM yelling: "Shear 'em if you got 'em!"
Crates can be put on their backs like on cargo mule-bots. Cargo will push their limits!

Spraycan sheep-people to leave them more ashamed of themselves, cuz no one will care about their chemicly colored wool anymore and they will have to shear themselves! HONK

Gross things are easily attached to them, like trash/banana peels/gibs.

Head slugs can easily fast hide in their wool.

Overall... SS13 is not a good place for so fragile "animals". Suffering is guaranteed

**Comment by nullAurelian** [comment]
A couple of things
1. Movespeed is busted in all things, and any increase is munchkin fuel. Don't increase movespeed. No amount of HP decrease matters if you just never get hit
2. There is enough shittery to go around without encouraging it with a 'race' designed for it.
3. Honestly? this whole lot of stuff seems to be asking for license to grief. If you want to make alternate character species a thing, leave them as cosmetic or no effect on game play. If you want to grief, make and play your own server.

**Comment by Buldinn** [comment]
> Overall... SS13 is not a good place for so fragile "animals". Suffering is guaranteed

I disagree completely, because of the environment of constant evil and horrible things that happen, a fragile race is very suited for game-play and perfectly fits into the already existing theme of the game.

Consider it "hard mode", I understand that most would prefer to powergame but not everyone is the same.

**Comment by Raptorizer** [comment]
I feel that adding NEW custom races is important, but not for this serverbase. Unitystation should be focused on relaying what races are standardized within ss13. Lizardfolk, golems, plasmamen, humans, androids, etc. 
[See here for TG races](https://tgstation13.org/wiki/Guide_to_races) 
[See here for YogStation races](https://wiki.yogstation.net/wiki/Guide_to_races) 
[See here for ParadiseStation races](https://www.paradisestation.org/wiki/index.php/Main_Page) 
[See here for Baystation races](https://wiki.baystation12.net/Main_Page)
