### ISSUE TITLE
Suggestion: Brig Changes

### ISSUE THREAD

**Issue by Mycah142** [unitystation/unitystation#3556]
**Current issue:** All parties involved with imprisoning a player are usually unhappy with the scenario unless they're brutal.

-  -Warden has to continually watch all prisoners at all times, as breaking the windows, until reinforced, are easy.
-  -Getting into the cell to heal/interact with the prisoner usually ends with the prisoner trying to disarm/damage the officer, which the officer will react usually lethally.
-  -Handcuffs only take 30 seconds to remove, so you can assume that literally any prisoner, once celled, is uncuffed. Trying to keep the cuff on them involves the Warden or an officer on each prisoner, repeatedly whacking them with a stun baton.
-  -Imprisoning someone is currently unfeasible, as both sec officers and the prisoners rarely err on the side of caution, and will act aggressively, as no one feels safe.

**Solution:** Simple, dynamic "prison break" system.

-  -Replace cell door/windows with a force field. Force field is powered by same system Sec is powered by (no separate grid). This force field is transparent, but act like a regular door, only letting wielders of allowed IDs through. These users will need to pass cleanly through, not "hesitate". It won't open like a door does. Authorized personnel just pass through unphased.
-  -When power is lost, Shutters drop in the fields' place. This removes visibility into the cell, but is a mechanical way for prisoners to not escape. A fail safe.
-  -These shutters can be opened from outside manually, using a crank. These cranks are similar to current shutter buttons, just take longer. Imagine instead of a button and power, it's a crank and you're manually opening/closing it by hand. Think of a garage door with a broken motor.

**How this changes things:** The prisoner, on their own, will have far harder a time to escape. But, someone on the outside can help them, or freak circumstances that lead to Sec losing power causing confusion amongst Sec.

It brings more excitement, involvement, and roleplaying/planning from players to escape from jail, and allows Sec to not just lock people into a cell and forget about them. Sec won't just kill people, because jailing is ineffective. So the prisoners either serve out their time, or figure out a way to convince someone to help them escape.

Just like real jail.

**Comment by Akronymus-git** [comment]
Maybe relevant #3265

**Comment by Skayland6909** [comment]
alright

> _"all parties involved with imprisoning a player are usually unhappy with the scenario unless they're brutal."_

70% of the rounds i am part of the Security team, i have never seen anyone unhappy with imprisoning system and i am not unhappy with it either, if a security guard goes brutal/lethal that guard should be jailed as this action is not supposed to happen at all, that's why the non-lethal equipment exists.
 The imprisoning of a player is as easy as this: catch the player, stun, handcuff, bring to cell, stun, leave him inside and leave, the freeing of a player is exactly the opposite, and it works, there is no unhappy parties besides the jailed player raging as always, but this is a common thing and its how the community behaves, this will probably be fixed with time as the new community understands how things work (you do something bad -> you get jailed)

> _"warden has to continually watch all prisoners"_

 that's his job, he is the warden, the guard of the brig, he is supposed to stay inside the Security Department, guard the armory and cells, its the only thing he has to do.
 

> _"until windows are reinforced"_

 reinforced glass and reinforced windows already exist, maybe the hitpoints should be touched a bit

> _"getting into a cell to interact with the prisoner ends up with the prisoner disarming the guard"_

 A guard should never go into a cell alone, even less if this is a dangerous prisoner who commited a 4xx (capital crime) or 3xx crime, going in groups of at least 2 (for example a guard and the warden) is standard procedure, the players roleplaying the security team just have to learn how to and what actions to take,

> _"the officer will react usually lethal"_

 an officer should never react lethally, if an officer reacts lethally he should be jailed for murder attempt/murder, since murdering a prisoner is something only the captain can authorize, an officer must use the non-lethal stunning weaponry he/she starts with, always

> _"Handcuffs only take 30 seconds to remove"_

 i agree this is bad, breaking handcuffs should be harder as in real life, but also should be noted that in real life prisoners don't stay handcuffed inside a cell either, the handcuffs are put/removed in the cell door before leaving/entering and/or used in the court. This means there should be different solution, which i will talk about in the end

> _"imprisoning someone is unfeasible... guards act aggressively, as no one feels safe"_

 Imprisoning people has variable effectivity, it depends of how toxic and how much rage the player has, just like the first point, this is not related to how jailing/security in general works, its related to how the community and the player-base behaves in the current state of the game, this will probably be fixed when the other departments are included and people actually have something to do besides killing each other like in a deathmatch or fps game

----

> _"the solution"_

makes no sense, and its not 'simple', also it doesnt fix the problem you describe, sorry
- first of all: like you stated in your first points, guards get disarmed by the prisoners, so a system where a forcefield is only passable by a player with a security or higher rank id, this means if a prisoner (like i said before and you too) disarms the guard he will get an id which he can use to leave the cell, so it wouldn't change much, unless the taser could go through it, but then whats the difference between the forcefield and the windoor used in tg maps? since a laser gun can go through glass, and this should be implemented soon, then the disarm problem wont exist anymore, so what's the point in adding forcefields? actually, i don't see the problem you are describing at all, since any competent security guard can go in and out of a cell without problems, AND the warden is supposed to stay in the brig and watch the prisoners (and the armory)
- second thing is about the shutters: if cells get shutters in the doors i am sure it would kill the round for many people, bad guards (RDMers or others) wont wait for the power to go out to close the shutters and perma jail people inside, like some actually do, this also makes the hope to escape for a prisoner (antag or not) banish. Shutters can also be used to easily gib people bodies (#3265), which is bad, would even be bad for the guards themselves if a prisoner manages to leave the cell somehow.
- third: crank? for now shutters do not use power, and personally i think they shouldn't even if it is not realistic, and a crank would be to much trouble, please leave the shutters alone with their buttons, they are ok and they work, also, if a windoor is implemented in the cells instead of a "forcefield" you wont need power at all for it to stay closed and therefor a shutter wont be needed.
- fourth: _"How this changes things:"_ no, just.... no. adding shutters and a forcefield doesn't add "excitement" at all, and there is no real "planning how to escape" if you make all the cells look like Guantanamo with shutters, electrified grills, super strong handcuffs and "forcefield"... just no, also how would a prisoner "convince" someone to help him escape if he probably has no headset and reinforced walls and shutters don't let sound pass thru?. _"just like real jail."_ Real jails have no shutters, neither forcefields, neither do the prisoners have handcuffs inside, and they only talk between themselves, the only way they talk with someone outside that could "Help them escape" is separated with a reinforced glass panel in a monitored conversation surrounded by cops and cameras, using a phone which records everything both the prisoner and the visitor say, do you want that? because that is real jail, and it would kill playability. _"allows Sec to not just lock people into a cell and forget about them."_ there is a different solution for this, keep reading.
- fifth: i think the problem you describe, about how hard is it for guards to enter/leave a cell or the warden having to stay there and guard them is not solved with the solution you offer, since your solution just contemplates how safe a cell is, and as i said before, the warden is supposed to guard the cells, that's his job. In discord you said the warden dies of hunger and can't go out, well, since the disarmed guards entering/leaving cell is not really a problem because any competent guard can do that, lets talk about a real solution to the only problem i see here

**My solution:**
- All maps should have a food vendor inside brig, and not only 10 or less donuts, so the warden doesn't die of hunger and can do his job of staying the whole round inside brig guarding the cells.
- The timer for cells has to be implemented, and it should make an annoying sound, so the warden remembers to free the prisoner.
- The airtight doors/doors have to be replaced with windoors and the disabler gun has to be implemented (weapon which goes through any glass) or the taser/laser gun(which is also a taser for some reason) should go through glass.
- Other departments have to be implemented so people have something to do and don't end up killing people because they are bored.
- The Spacelaw book should be implemented, and the item should be mapped in a visible place like a table with other useful stuff like handcuffs and donuts so the guards actually see it and get interested, it should also appear in vendors. i will add this a suggestion for the 0.5 roadmap, since its related to the "implement books" suggestion.

Another thing that could be implemented in the long term is the credits for players, so people actually do their job to get the payment in the "payday" like in tg, so they use this money to buy food or clothing. This would encourage people to work together or at least do their jobs instead of becoming criminals, also after a crime: reducing the player's credits could also be part of the punishment.

**Final notes**
 The game is still in development, some people come from SS13 but others are new, RDM is to be expected, criminals are to be expected, bad security and noobs are to be expected. A new community is being built after all, and this is part of the process. If you or someone cant stand the hard work of being a warden (guard armory, guard cells, stay in brig, manage security records, etc) then, please try another job, there is plenty. but don't say the system doesn't work if your argument can be translated to "i am not competent enough to go out and get food to stay in brig or guard the cells". sorry, i don't want to sound rude, i just want to say, sometimes we are just not good for the job we like.

**Comment by Evan-R-Rogers** [comment]
Well, without leaving an epic poem in my wake: I'd first suggest implementing the wall-mounted flashers. The warden presses a button and easy-peasy-orange-squeezy we've got an incapacitated prisoner!

For the crank: If I'm being honest thats a bad idea. I understand where you're coming from but that just isn't...fun. Yeah.

As I've said before in the Discord: prisoners, perma-brigged or not, alike should at least have one modem of escaping. Taking the Outpost map for example, prisoners in the brig can smash through the windows on the inside _or_ the outside given if they're not shuttered and even then they still have a fair chance if they were to keep it up; if they get out its the Warden's fault for not stopping them. As for the perma-brig the only way out is through the glass dome of which leads to space, prisoners in there have a fair chance of dying but at least it leaves some room for them to escape or be rescued.

**Now for my _possible_ solutions:**
- If players, the Warden specifically, happen to either die or forget about a prisoner then there could be a sort of auto release mechanism that is tied to the timer. Set a time, such as a minute or so, and forget about it.
- Wall-mounted flashers that the Warden, or others, can activate via a button press.
- Somewhat unrelated but since we're on the topic of security: metal detectors/millimeter scanners/other scanners to place at the doors of the brig and sec to detect weapons on individuals that are not supposed to be carrying them.

**Comment by Skayland6909** [comment]
Yea the flashers, thanks, i forgot about that one, i added it to my suggestions for 0.5 goals.
 About the auto-release timer i don't think is a good idea unless there is a way to secure that no one else comes inside the cell when the door opens and it opens to the outside of brig and not to the inside (so the prisoner doesn't get trapped inside brig anyways)

**Comment by Evan-R-Rogers** [comment]
> "...when the door opens and it opens to the outside of brig..."

Not so sure if TG has this, looking through the wiki it doesn't, but on Goon there is a release chute of sorts that opens up and the prisoner falls through to a sort of lobby/exit area instead of the door opening. I did say this in the Discord and it wasn't very well received, however.

**Comment by Mycah142** [comment]
> **My solution:**
> 
> * All maps should have a food vendor inside brig, and not only 10 or less donuts, so the warden doesn't die of hunger and can do his job of staying the whole round inside brig guarding the cells.

Would be awesome. Outpost I think has none, if it does, it's emptied by someone within a minute. Maybe one specifically in the armory?

> * The timer for cells has to be implemented, and it should make an annoying sound, so the warden remembers to free the prisoner.

Yeah. Trying to fill out criminal records and trying to keep track of time while discouraging someone from beating windows, while another officer or two are bringing in dead bodies to put into cells gets annoying. An easy timer with like a 1, 5, 10, 15 or even just custom timer touchable by Warden, HoS, +, would assure the officers and prisoner that the prisoner isn't in there forever. I didn't think of a visible/audible timer.

> * The airtight doors/doors have to be replaced with windoors and the disabler gun has to be implemented (weapon which goes through any glass) or the taser/laser gun(which is also a taser for some reason) should go through glass.

Aren't they easier to destroy without breaking the bed apart? Maybe the door can have a mail slot in it that can hold an inventory, which can have food or other stuff put into it.

> * Other departments have to be implemented so people have something to do and don't end up killing people because they are bored.

I agree. Robutts when?

> * The Spacelaw book should be implemented, and the item should be mapped in a visible place like a table with other useful stuff like handcuffs and donuts so the guards actually see it and get interested, it should also appear in vendors. i will add this a suggestion for the 0.5 roadmap, since its related to the "implement books" suggestion.

I hear much about it but it is usually just something lawyers yell about and then the chaplain pulls out his sword.

> Another thing that could be implemented in the long term is the credits for players, so people actually do their job to get the payment in the "payday" like in tg, so they use this money to buy food or clothing. This would encourage people to work together or at least do their jobs instead of becoming criminals, also after a crime: reducing the player's credits could also be part of the punishment.

I was reading the TG Wiki and saw credits mentioned a ton. If this is supposed to be TG remastered, then I ASSUME it'll be a thing? Though I saw Doobly giving it shit. Not sure.




> If you or someone cant stand the hard work of being a warden 

Lost me there mate, your argument devolved into "get gud". You were doing fucking wonderfully, even though your main grief was with essentially "just play better", but you then turned it personal. Not how you win an argument.

I appreciate the counter points and the differing solution though.

**Comment by Skayland6909** [comment]
as i said i didn't want to sound rude or personal. i just wanted to say that sometimes we cant do the job we want the way we would want because we are just not good for it, and we gotta deal with it, if we cant do a job its better to try another job instead.

**Comment by Mycah142** [comment]
So maybe a simpler change?

The "Flashers", though I find that they sound really aggressive. A room wide stun baton.

Timer, like the the Shuttle ETA sign, so everyone can see it. Audible sound on completion.

**Comment by Skayland6909** [comment]
the flashers are not stun batons, these only blind the prisoner for a few seconds, just like the welder does on tg station

**Comment by NoooneyDude** [comment]
The issues described here have been somewhat alleviated by the addition of door cell timers, reinforced windows and shutters.

**Comment by corp-0** [comment]
Agree with Nooney. Please reopen the issue if there is any further discussion to be done or better yet, create a new issue with specific criteria.
