### ISSUE TITLE
ad a fullscreen borderd mode and geforce exp minimizes unitystation

### ISSUE THREAD

**Issue by makuru-org** [unitystation/unitystation#3570]
its annoing when i tap out that the game disappears

**Comment by Misterixmax** [comment]
We need simply have the possibility to launch game via hub with " -popuwindow" as startup config. Right now we can only launch build exe with such params. In addition - it's better to have a possibility to use customizable startup params for build inside hub.

@Makuru-DD For now: Simply go to build folder inside hub, make a shortcut for build's exe OUTSIDE OF HUB AND BUILD FOLDER (otherwise hub may die, bug), add startup params -popupwindow
If you don't know how to change startup params for shortcuts - google: ksp -popupwindow, there will be a lot of answers on forums.

Also, you have to create a new one or chamge old shortcut's folder adress to a new build number every update.

**Comment by makuru-org** [comment]
@Misterixmax so now for somone how just starts to learn comuter science
and i cant find annything in the KSP wiki
but thanks
