### ISSUE TITLE
Wallmount visibility

### ISSUE THREAD

**Issue by TheBimmer231** [unitystation/unitystation#389]
# Preliminary information
## Category
BUG

# Report
## Current Behavior
Wallmounts are visible on the wrong side of a wall

## Expected/Wanted/Requested Behavior
They should only be visible on the side the player is actually on.

## Requiremetns

* [ ] Hide wallmount when player is not within the front 180 degrees of the wallmount

**Comment by Ornias1993** [comment]
Shouldn't this be fixed in the tilemap upgrade?

**Comment by Ornias1993** [comment]
This problem exists in both Develop and Tilemap_Overhault, with the current camera code.
The fix is moving the object in front of the wall, offsetting the sprite onto the wall and let the camera check the object location instead of just the sprite.

The two parts are already executed in tilemap_overhault.
But even so, the current camera script still does not check the object location, so even in tilemap_overhault this will still show up.

So the solution would be for someone to add a check if the object location is in sight, instead of just the sprite.

**Comment by Ornias1993** [comment]
@DooblyNoobly This can be labeled as BUG
It is reproducable and known.

**Comment by chairbender** [comment]
Looking into it.

**Comment by chairbender** [comment]
Gif of error - notice how wallmount is still visible when I leave the room:
![wallmount](https://user-images.githubusercontent.com/1329062/50376797-6608e300-05c7-11e9-8458-1bd65ed19ac0.gif)

**Comment by chairbender** [comment]
FOV is not actually hiding the wall mounts (you can see it in my screenshot), I'll need to set this up as well. I think they just need to get the same material that the other FOV-obscured objects have

**Comment by chairbender** [comment]
It's absolutely not easy to implement. Our current FoV logic does not actually obscure any walls, and if it is modified to obscure walls it starts obscuring the first wall itself, meaning it would hide any wallmounts on the wall nearest to the player. The challenge is in figuring out how to leave the nearest wall un-obscured by FoV but leave all other walls obscured.

**Comment by chairbender** [comment]
...let me put that a different way.

It's absolutely not easy to implement as a novice unity / shader dev. But after a bit of trial and error and quite a lot of reworking / rethinking I think I've found a way we can do it all in the shader.

**Comment by chairbender** [comment]
It was pointed out that the WallmountBehavior is doing too much redundant GC:
![unknown](https://user-images.githubusercontent.com/1329062/50656144-1d4a1600-0f47-11e9-9a08-de23b1904872.png)

Per @MrMeatpie -
"At least, we should get components once at start, not twice each frame(edited)
And it looks like you are treating render.enabled as indication of visibility, so it runs over all wall mounts in the scene(edited)
Checking that sprite bounds are intersecting with camera bounds would  indicate that sprite is actually visible
I would just check by arbitrary range from camera position. It would be less precise but it might be less expensive than bounds test. Should cull at least 80% of redundant tests

Or, We can just use OnWillRenderObject() instead of Update, since it handles visibility check. That would require to reattach behavior from parent on to sprite itself(edited)
in that case we could reliably test against Camera.current position, not player position. That would help in case if somebody would want to implement remote cameras.
"

Reopening this so I can apply the above mentioned approach to reduce the amount of gc

**Comment by chairbender** [comment]
Re-opening this for one more thing noticed by Foma - sometimes the sprites flicker when you move from visible to invisible:

"In the main hallway, at the T junction, if you move left and right in the gap where the locker is it happens too, unsure if that can be fixed the same way"
