### ISSUE TITLE
Admin Trello enhancement / replacement

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#4159]
# Issue

Our admins are currently using Trello to keep an overview of bans and warnings.

This system works, but there are issues:
* Duplicate entries of the same user are possible
  * Manually searching for duplicates is tedious
* There is no in-game integration or direct linking to accounts
  * Which makes mistakes or duplicates even more likely.
  * Bans which were not entered into Trello are difficult to track
* Some Trello features are locked behind a paywall
  * ... Which we could circumvent by paying 4$ / month
* Trello is difficult to use
  * It's a Kanban board, not a ... ban management tool.

(Leave a comment if there's more!)

# Suggestions
Perhaps there's something we could do to save our admins some time.

* Trello has an API which we might be able to use. https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/
  * This would let us integrate common Trello actions in-game.
* We could switch to a different tool.
  * Google Sheets (Has an API, too)
  * ...
* We could make our own tool.
  * Probably not feasible?

**Comment by craftxbox** [comment]
> Duplicate entries of the same user are possible

Easy solution. Search for the user you're checking.
> Manually searching for duplicates is tedious

Have you seen this? https://crxb.tk/t0m510.png
> There is no in-game integration or direct linking to accounts

There is a reason for this. Usernames are not unique, UID's are clunky to deal with. 
> Which makes mistakes or duplicates even more likely.

Again, Search.
> Bans which were not entered into Trello are difficult to track

This is on YOU if you do not enter a punishment into trello, and you WILL have very many angry admins on you if you do this repeatedly.
> Some Trello features are locked behind a paywall

Can you provide an example on how these paid features significantly improve things?
> Trello is difficult to use

I certainly cant say anything without bias here but, what? Trello is *incredibly* easy to use, enough that ive introduced many people to it and have not had to teach them *anything* on how to use it.

##

> Trello has an API which we might be able to use

Sure? if you can figure out a *secure, configurable* way to do this.
> We could switch to a different tool.

Unfeasible.
> Google Sheets (Has an API, too)

You want to switch to *google sheets* over trello? are you mad? sheets is EXPONENTIALLY more difficult to deal with.
> We could make our own tool.

As you mentioned. Unfeasible.

##

This entire issue seems to me like making an issue out of where there really isnt one, Trello search is *very intuitive* and duplicates are impossible if you actually use it, it is not difficult to do even the most *basic* of trello card, click the button, type the name, add a punishment label, select the rule break, and press join card. Unlogged punishments are the fault of the admin not doing them, rather than  a fault of the tool.

**Comment by daalta** [comment]
Hi @craftxbox , thanks for discussing this!

While I agree with your points in general, I still believe that making our admin tools easier to use is something we should strive for. But it sounds like you're happy with Trello, which is good to hear! 😙

----------------

About duplicate users: I agree that Trello's search *generally* alleviates the issue, but duplicates are definitely possible. We track user IDs via screenshots, which cannot be searched. And occasionally we accumulate several cards with the same name.

Having some sort of in-game linking might be interesting. Trello's API is accessed via personal access token, which our admins could set up on their own computer.

> You want to switch to google sheets over trello? are you mad?

I don't think Google Sheets is a great solution (which is why I created the Trello board 😉). It *is* an alternative though and has scripting features. I was hoping that some of you might know more Trello / "ban management software" alternatives?

> Can you provide an example on how these paid features significantly improve things?

We're currently using [Trello Gold](https://trello.com/en/gold ) because you all signed up for Trello! :) 
But we've not really used any of the advanced features because our credit will expire in a few months.

I suppose as long as we're only using custom fields we might be fine with Trello's standard version, though automations would have been interesting.

Some interesting features are:
* Higher attachment limits (for attaching videos)
* Higher plugin limit (3 plugins instead of 1)
  * Custom fields would not be possible without these
* Higher butler automation functionality
---

In the end I'm not the one using the Trello board. I'm hoping that we end up with a tool that works in the long run and which our admins are happy to use! 🙂

I'm a bit scared of an admin going on a rampage and destroying our entire board by the way, and Trello doesn't have a version history or an automatic backup system.

**Comment by Ranzarth** [comment]
Trello is an outside tool that just makes it very tedious to use overall, a built in alternative in the game is the best option, just like how byond ss13 does it. A built in solution would allow for quicker note taking, which would make it easier on the admins and less of a pain to do, it will also allow us to have an automated system of flagging accounts with previous note and ban history. 

This built in alternative could also build into the eventual ability to search all accounts that have connected to the server, and would have a detail profile panel we can view for those notes, ban history, the ability to ban when they are not even connected, last time they connected, and also previous log history. Since it would all be in the game, you could also integrate it into the discord to have the ability to view a player's notes, logs, and ban history, all in the comfort of discord

There is much more to what can be added in, but overall, having the notes be eventually integrated into the game is the best and only option in my opinion.

**Comment by craftxbox** [comment]
>  very tedious

again, what???
> a built in alternative in the game is the best option, just like how byond ss13 does it

This isnt within the scope of this issue. This issue is about replacing and/or otherwise enhancing the current solution. Not creating an entirely new one. While yes, This is the *best* option, its simply not feasible at this moment. The rest of your comment is purely opinion of what you want to see, so as such I will not comment on it.

**Comment by Ranzarth** [comment]
> **This issue is about replacing** and/or otherwise enhancing the current solution. **Not creating an entirely new one.**

You just contradicted yourself in this statement.

Trello is not something we should just stay with forever, I am not sure why you would defend this system so strongly. Having our own integrated system, even with just a simple notes panel on each account with ban logs would still be better than trello.

Trello is slow to use as you have to search manually if the account name is already in the trello, enter in a bunch of account info, pictures of the account tag and/or PM conversations, etc etc, this is not a great and/or quick system.

**Comment by craftxbox** [comment]
> You just contradicted yourself in this statement.

You knew exactly what I meant here.
>  I am not sure why you would defend this system so strongly. Having our own integrated system [...]  would still be better

See:
> While yes, This is the best option, its simply not feasible at this moment.

I defend the current system because there are no good readily available replacements, it REALLY IS NOT AN ISSUE IN THE FIRST PLACE, and would be a *waste* of time to migrate to a new, most likely inferior platform. If you would like to make an integrated system, the Git is open, feel free to. But right now? All it will do is take up extra development time that could be spent *elsewhere on core gameplay elements*.

> Trello is slow to use as you have to search manually if the account name is already in the trello, enter in a bunch of account info, pictures of the account tag and/or PM conversations, etc etc, this is not a great and/or quick system.

You type in the  box, you see if there's a card, if yes, click it, if not, click the new button.
You type the username, you type what happened, you label what you did to them, press 'join card', now you're done. Certainly adding those details is nice, but its really NOT hard and certainly NOT tedious. I Very rarely even HAVE to log an interaction in trello, and if i do, it takes 20 seconds, maximum.

**Comment by PerfectTangent** [comment]
this is a holdover from when official servers were a thing, and is no longer relevant
