### ISSUE TITLE
Construction: Create new wiring Prefab B:25

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#417]
This will be the beginning of the electrical system. We need to first create a prefab that will turn into all of the different wiring configurations used when laying down electrical wiring. Our focus here is to first create a wiring prefab that can be used with the map editor. And when the rotate hotkey is pressed it will change to all the different wiring configurations. We do not want to follow tgstation here as wiring is a bit clunky, instead we will follow similar to Stationeers where you can scroll through the different types of configurations and then apply them to the grid.

After this job is done we will then focus on in game wiring where the engineer will hover over the tile he wants to lay the wiring on and he then will be able to scroll through the different configurations with the mouse scroll wheel or keyboard shortcut before clicking and applying it to the tile.

Wire cutters will just remove the wiring for the whole tile and spawn a wire prefab to be picked up.

Criteria:

- Build a universal wiring prefab that will turn into all configurations and colors
- Make it work with the map editor (scrolling through the configs with rotate hotkey)
- Make sure wiring is positioned below floor tiles and above maintenance tiles in the spriterenderer sprite order

This job is for stage 1 of wiring only (Map editor functionality). After this job is completed we will then move to stage 2 which will be the in game use of the wiring prefab in a separate bounty job.

Bounty: 25usd paid via paypal after successful merge

**Comment by krille90** [comment]
"Make sure wiring is positioned below floor tiles and above maintenance tiles in the spriterenderer sprite order"

This actually should depend since in ss13 you can also put wiring on the floor, currently we don't differ between maint floor and 'normal' floor. This is something I had planned when we move to tilemaps.

**Comment by DooblyNoobly** [comment]
Just changing the sprite order of maint tile below any floors should do it and then slot the wiring in between those two values.

**Comment by PrPleGoo** [comment]
>This actually should depend since in ss13 you can also put wiring on the floor

On TG maybe but looking at their code it is a bug report waiting to happen. Their wire structure does not store its vertical location so laying wire on top of floor plating would connect it to the wires under the plating anyway since it looks for wire structures in the loc. Plus wire's error message suggests that it shouldn't be possible.

Wires should be below floor plating.
