### ISSUE TITLE
"Running" while malnourished shouldn't make you slip on wet floors.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4351]
## Description
If you're malnourished and "running", you are still able to slip on wet floors. I don't think this should be possible as if you're malnourished and "running" you are moving at roughly the same speed as you would be while walking and well-fed. 

It is also frustrating to be malnourished and having to walk due to wet floors since you move at an absurdly slow speed, especially if you happen to also be wearing clothing that slows you down.

**Comment by stvnksslr** [comment]
I would argue its the intent of the speed that should determine whether you trip or not vs the actual speed. 

When you run malnourished you are still rushing and therefore should be susceptible to slipping even if your moving slower because of a negative status.

Disagree on this being a bug either way.

**Comment by fomalsd** [comment]
that's a fair point actually. maybe make malnourished walking speed even lower than 3 and this one can be closed

**Comment by yoysam** [comment]
should we increase the staving penalties to balance it out

**Comment by yoysam** [comment]
the pull request fixed it

**Comment by Mute-Man** [comment]
PR #4678
