### ISSUE TITLE
UX/UI Style Guide First Draft

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#4376]
### Description;

- Produce a first draft of a guide that sets a clear direction in how the look and feel of the UI should be presented to the player. This guide will be used by multiple developers with differing experience levels to ensure consistency of UX/UI over the course of the project
- Produce the document on Google Docs with a table of contents with links to each section on the first few pages (later I will upload the final draft to the dev wiki site)

### Tasks:

- Determine all of the important areas that should be addressed in this guide
   See these links for research:
-- https://www.linkedin.com/pulse/game-ux-style-guide-why-do-you-need-one-om-tandon
-- https://www.toptal.com/designers/ui/ui-styleguide-better-ux
-- https://imgur.com/a/Y2HV1

- Determine a set of core values that will drive the rest of the design process (i.e. Try to reduce clutter, simplify where possible, which look are we going for?)

- Determine a direction or vision. I'm not an artist so I want to see what your vision is for the look of the UI parts of the game. Provide clear examples of the elements that make up your vision.

- Based on the research, goals and vision write a first draft of the design document. List each section under a sub title and have a link to it in the table of contents. 

- Have the first draft reviewed by the heads of staff and get feedback from the community

**Comment by KWVance** [comment]
Leaving a comment as requested

**Comment by Dropgunner** [comment]
Long story short: We need a bounty for a UI/UX designer making a decent whitepaper for designing user interfaces and first-time user experiences.

Each UI should be accented with the department signature colour like the cargo UI is accented with Orange.
We should generally aim for a CRT-looking style to the screens.
So there needs to be a list of departments and if existing, what signature color is currently used
Example:
Cargo - Orange
Medical - Light blue
Security - Red
Science - Purple
Engineering - Yellow
Service - Green
a list of what each department's UI does. Security has different features/tasks, then medical and science.
Cargo - Cargo Handling UI
Medical - Medical records, suit sensor tracking, genetics, cloning and chemistry
Security - Security records and prisoner management, security cams
Science - Research and Inventions, xenobiology and AI management
Engineering - Reactor management, power monitoring, atmospherics monitoring
Service - Botany genetics, drinks dispensing

. just doing analysis on something where no ux consideration was paid to before going this far down developent is crazy tedious. just making a list of complaints won't help because there will be a million arguments be made by members who say that some things having a horrible usability are cool because it's the same as the original. so not only do I need to work myself through an experience I don't understand whatts there, why or whats the expected experience to happen but also make ideally some visualiation of what is needed or done differently better. shit like inventory handling, "looting" or just even having a player understand what he is supposed to do, what he can do and how is stuff that should have been concepted before setting up interactions and putting stuff into code.

the ui stuff i got in yesterday, trying to figure out whats is its variables, inteentions and reasons. i asked for a feature list, a detailed list but so far got mostly headlines and generaal descriptions. so I'm gonna start with the interaction with items, inventory and environment since it's the most complete chunk of self-punishment to straighten out.

**Comment by Bod9001** [comment]
No longer time bounty on this, 
as time of writing, draft for UI has been finished, and a few concepts for in game UIs but progress has been non-existent recently

**Comment by PerfectTangent** [comment]
closing as the UI/UX team has disbanded and the major player UI overhaul has been completed.
