### ISSUE TITLE
Server NRE when locker is opened after grenade exploded in it

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4690]
## Description
Server NRE when locker is opened after grenade exploded in it.

![unitystation_kwij5Gqqmf](https://user-images.githubusercontent.com/6926225/88246978-48928280-ccf0-11ea-9b02-514b6ff1c8a1.png)

### Steps to Reproduce
1. As the host on a development build, place an activated grenade in a locker and close it.
2. Step back and wait for the explosion.
3. Attempt to open the locker and observe the NRE produced.

**Comment by JesterX666** [comment]
Another Exception caused by the same way:

MissingReferenceException: The object of type 'ObjectBehaviour' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[T] () (at <1245d947a91b4a14b7c7e2c7335512b2>:0)
ClosetControl.OpenItemHandling () (at Assets/Scripts/Closets/ClosetControl.cs:465)
ClosetControl.ServerHandleContentsOnStatusChange (System.Boolean willClose) (at Assets/Scripts/Closets/ClosetControl.cs:453)
ClosetControl.OnWillDestroyServer (DestructionInfo arg0) (at Assets/Scripts/Closets/ClosetControl.cs:148)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <1245d947a91b4a14b7c7e2c7335512b2>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <1245d947a91b4a14b7c7e2c7335512b2>:0)
Integrity.CheckDestruction () (at Assets/Scripts/Health/Objects/Integrity.cs:264)
Integrity.ApplyDamage (System.Single damage, AttackType attackType, DamageType damageType) (at Assets/Scripts/Health/Objects/Integrity.cs:221)
Explosion.DamageObjects (UnityEngine.Vector3Int worldPosition, System.Int32 damage) (at Assets/Scripts/Explosion/Explosion.cs:149)
Explosion+<ExplosionRoutine>d__11.MoveNext () (at Assets/Scripts/Explosion/Explosion.cs:84)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <1245d947a91b4a14b7c7e2c7335512b2>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Explosion:Explode(Matrix) (at Assets/Scripts/Explosion/Explosion.cs:34)
Grenade:Explode() (at Assets/Scripts/Weapons/Grenade.cs:148)
<TimeExplode>d__16:MoveNext() (at Assets/Scripts/Weapons/Grenade.cs:104)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by NoooneyDude** [comment]
Interestingly I couldn't reproduce the issue in morgues, which also uses parentContainer stuff. The morgue is destroyed as expected.

**Comment by JesterX666** [comment]
Fun story : The null item is the grenade itself!
Before explosion, the closet contains 5 items
After explosion, the closet contains 6 items (one of which is null)
