### ISSUE TITLE
Add a crafting system.

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4733]
A flexible systems needs to be created for crafting items with multiple components.

Needed for items such as:
https://tgstation13.org/wiki/Makeshift_weapons

or all the food types:
https://tgstation13.org/wiki/Food#Crafting_Recipes

**Comment by corp-0** [comment]
Can you describe how the system should work? For the sake of having a common ground and to determine if the requirement is satisfied by whoever wants to implement it

**Comment by ThatDan123** [comment]
Pretty sure the TG system is the tile you are facing is checked, and when you open the crafting UI, it is split into categories(food, weapons...) and if the recipes are possible(If all items needed are in front of you), then you start crafting which is a progress bar.

**Comment by NoooneyDude** [comment]
Related to PR #4564.

**Comment by corp-0** [comment]
Is it only the tile you're facing or all tiles in your reach?

**Comment by ThatDan123** [comment]
ngl i didnt use the crafting system much

**Comment by corp-0** [comment]
Aight, if someone who knows better and can give us the criteria/requirements the system needs to satisfy and we can add them to the OP that'd be great.

**Comment by PetMudstone** [comment]
- The crafting system uses items and reagents, **requirements**, that are either on reachable tiles or in your external inventory slots (pockets, hands). Requirements are used to create other items, called **results**.
  - Reagents are sourced from items that hold them.
- Some requirements are also **parts**. Parts are either put into the result or otherwise alter its behavior. 
  - For example, what kind of bottle (or carton) you use to make a molotov cocktail affects its volume (and safety) and its held reagents are transferred over to the resulting molotov.
  - For another example, whether you use a normal glass shard or plasma glass shard affects the resulting spear's damage and sprite.
- The act of actually crafting is set to a **timer**. The timer is set in seconds and when it finishes, the requirements are used up and the result is produced.
  - The timer should be a float value, as /tg/ timer values are float values.
-  Recipes can need one or more **tools** to perform. Tools are not consumed upon crafting completion.
   - For example, the recipe for a motorized wheelchair needs a welding tool, a screwdriver, and a wrench to perform.
   - Meanwhile the recipe for a securitron only needs welding tool to perform.'
- Recipes can require multiple of one requirement.

**Comment by corp-0** [comment]
Where does it look for requirements?

**Comment by PerfectTangent** [comment]
closing in favour of #6158
