### ISSUE TITLE
False walls don't smooth with actual walls and are too obvious. B:50

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#4746]
## Description
Right now, false walls don't smooth with real walls. This means that it's quite obvious if a false wall is present in a line of normal walls.

Where could the false wall be? 
![image](https://user-images.githubusercontent.com/38266309/88953525-ec7ab180-d24d-11ea-8ee9-f5f44ffc1cec.png)<details><summary>Spoiler warning</summary>
  It's right above the vending machine with a boot on its screen.</details>

False walls just aren't secret enough, which kinda defeats the point of making false walls. Having them smooth with real walls (and also other false walls if you put them next to each other for some reason) would actually make them secret doors as intended.

**Comment by fomalsd** [comment]
yeah, they aren't meant to be like that and certainly were smooth when they were first implemented (but had a bug with closing instead)

**Comment by PerfectTangent** [comment]
Bounty status bestowed. Valued at 50 USD.

**Comment by MaxIsJoe** [comment]
Heads up for people working on this in the future

ConnectedTiles do not use SpriteSOs and instead use a sprite sheet to draw tiles, you should probably make false walls a connected tile with tile interactions rather than a prefab, but this will require you to find a way to sync the door's state to everyone.

Alternatively, you could make a script that sits on the falsewall prefab that tries to find the nearest wall to blend to when it spawns by copying the wall's sprites but unity's tilemap system does not provide you with the sprite as seen in-game directly so you'll have to figure that one out.

Here's a script to get you started that doesn't work because I couldn't grab the sprite data that i want because of the problem i mentioned above.

```cs
namespace Objects.Doors
{
	public class FakeDoorTileBlend : MonoBehaviour
	{
		private SpriteHandler sprite;
		[SerializeField] private RegisterTile registerTile;
		[SerializeField] private LayerTile tileToBlend;


		private void Awake()
		{
			sprite = GetComponentInChildren<SpriteHandler>();
			Blend();
		}

		private void Blend()
		{
			var location = registerTile.LocalPosition;
			for (int i = 0; i < 4; i++)
			{
				var tile = TargetTileNearby(LocationToCheck(i, location));
				if (tile == null || tile is not ConnectedTile c) continue;
				sprite.SetSprite(tile.PreviewSprite);
				return;
			}
		}

		private LayerTile TargetTileNearby(Vector3Int position)
		{
			var tile = registerTile.Matrix.MetaTileMap.GetTile(position);
			if (tile == null) return null;
			return tile == tileToBlend ? tile : null;
		}

		private Vector3Int LocationToCheck(int direction, Vector3Int directionToCheck)
		{
			switch (direction)
			{
				case 0:
					directionToCheck.x += 1;
					return directionToCheck;
				case 1:
					directionToCheck.x -= 1;
					return directionToCheck;
				case 3:
					directionToCheck.y += 1;
					return directionToCheck;
				case 4:
					directionToCheck.y -= 1;
					return directionToCheck;
			}
			return directionToCheck;
		}
	}
}
```

**Comment by PerfectTangent** [comment]
bounty paid.
