### ISSUE TITLE
Traitor Objective View Action

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4802]
Make an action ( see mime powers ) for traitors to repeat their objective in the chat.

Or make a general antag UI screen which can be used to have a description of the current antag type and objectives.

**Comment by JustinTrotter** [comment]
I’ll try taking this one. Would it also be reasonable to just put the objectives in the personal notes? That’s how I remember it being kept track of on legacy servers.

**Comment by Akbadain29** [comment]
@JustinTrotter I tried figuring out how to access the Notes Tab but since it is an InputField, I thought you can only input text into the Note box, the only events you can manipulate in the editor are On Value Change and End Edit which means it's probably impossible to paste the objectives in.
I think it would be better making another nettab in the top right corner with the heading "Obj." which when you click on it, displays a string. Admins have an extra tab which are similar to that will only appears if the server validates that the player is an admin, the same could be done for an antag and the objectives.

Well, the CharacterCustomization InputField for the characterNameField makes it paste without an issue fine, they use a button to randomise the text of the name and update the name inside the field. But with the Notes Tab, I have not been able to find a way to access the Notes Tab's InputField through the NetworkTabManager.cs or the UIManager. The clientTabs[ClientTabType.Notes] didn't really have a reference to the field either.

**Comment by JustinTrotter** [comment]
@Akbadain29 I was actually able to paste objective in it. I was stuck on dealing with network details before my schedule changed. I’ll see about picking this up to continue. Your idea sounds less messy to implement anyway.

**Comment by PerfectTangent** [comment]
this was completed. Can't find the relevant PR, tho. Closing.
