### ISSUE TITLE
Bursting out of a closed locker twice stops all movement

### ISSUE THREAD

**Issue by Em3rgencyLT** [unitystation/unitystation#495]
# Preliminary information

## Category
BUG

## Bug: Release or Dev?
Dev

## BUG: Version
Develop

# Report
## Current Behavior
If you burst out of a locker by moving twice, you are prevented from moving altogether

## Expected/Wanted/Requested Behavior
You should be able to burst out of lockers as many times as you want

## Steps to Reproduce
1. Close yourself into any locker
2. Move in a valid direction. Locker should open and you will move out of it.
3. Repeat steps 1-2
4. Repeat steps 1-2 again. This time, you will be prevented from moving completely.

**Comment by Em3rgencyLT** [comment]
Possible, but unlike #494 this triggers an error at step 3.

![image](https://user-images.githubusercontent.com/15195221/33516252-523a65b6-d778-11e7-81be-b30ce4218a28.png)

**Comment by DooblyNoobly** [comment]
Ah yea, a position is added to the PlayerSync action queue (and the others are cleared I think?) so that the server and the client are both at the same position when the player leaves a closet (thus canceling out prediction). This is to make sure the player is at the right position when the closet is dragged around with a player in it. Looks like the second time around something goes wrong...

**Comment by Em3rgencyLT** [comment]
Working on it now. Dibs :D
