### ISSUE TITLE
bans are easily avoided, creating more significant stress on admins 

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#5048]

**Comment by PetMudstone** [comment]
Well, I was gonna make an issue on this already but oh well. I'll just copy and paste what I had already typed up below:

## The ability for admins to ban players who have disconnected.
Currently if a player leaves the game there is no practical way for admins to ban them afterwards. Because of this, it's completely possible to evade bans just by leaving before admins have the chance to ban you. As such, the ability to ban people who have left the game would be useful in catching these evaders.
