### ISSUE TITLE
firelocks are not syncing

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#5107]
## Description

happened on regularstation as a latejoiner. I'm unaware if this happens all the time or not

![image](https://user-images.githubusercontent.com/701959/92982342-20afd780-f474-11ea-96a8-26add99dd942.png)
this is from an admin 

![image](https://user-images.githubusercontent.com/701959/92982362-32917a80-f474-11ea-8fb8-858bc931558c.png)
this is from me

**Comment by PetMudstone** [comment]
I believe something similar happens with shutters and blast doors too. You can join a round in progress and closed shutters/blast doors will appear open. Notably, since closed shutters and blast doors are opaque unlike the firelocks above, their opened sprites will partially block vision though not completely. 

I reckon it happens with all other types of doors, but since most of them are automatic it isn't too noticeable.

**Comment by Aranclanos** [comment]
Fixed by #6047
