### ISSUE TITLE
ScriptableObject Singletons causing slight frame hitch when it tries to find the instances

### ISSUE THREAD

**Issue by Akbadain29** [unitystation/unitystation#5126]
## Description
SingletonScriptableObject probably needs to be rid of resources loading code (especially LoadAll) as it actually loads the whole asset database and then searches it. See lines 19 to 31 in SingletonScriptableObject.cs.

Doobly believes its best to make the singletons managers, put them in the managers trees and they then reference the Scriptable object.

**Comment by NoooneyDude** [comment]
Yes, it does appear this way can cause performance issues - `45 ms`, which is a noticeable hitch. See the attached image. The profiler sampled all of the `Instance` getter in `SingletonScriptableObject`, except for the returning line - named `SO init`.

I noticed the class documentation hints that the SO lookup should only take place if the SO is not defined via inspector, but the field is static so that is not possible.

![SO init profiled](https://user-images.githubusercontent.com/6926225/93662985-701b8680-fab8-11ea-91f8-18f505ba8835.png)

![profile 2](https://user-images.githubusercontent.com/6926225/93663257-875b7380-faba-11ea-80fd-61b28ea66fb5.png)
