### ISSUE TITLE
The ability to add to a non-mainstation matrix by building lattices on empty space while standing on said matrix.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5143]
## Description
The ability to expand the area of a matrix, such as a shuttle, would be helpful. This could possibly be done by having players build lattices onto space while standing on a tile on a non-station matrix. When this is done, the new lattice tile should belong to the matrix the player is standing on instead of the default station matrix as is currently the case.
This would be helpful not just for expanding matrices such as shuttles, but for repairing holes in them as well.

One of the remaining parts of #2463

**Comment by Akbadain29** [comment]
This also relates to shuttle construction from scratch I think. In that case, a player has to put a tile down in space without anything adjacent to - i.e. expanding the matrix for the first time - it otherwise will be considered part of an existing matrix. The way I believe we can get around this is creating an object (called something like a my-first-shuttle crate) which you pull into space (with a minimum 4 x 4 of empty space around it to commence building). When opened, it assembles the first tile of the shuttle matrix (catwalk, underfloor, floortile, with the open crate on top) and also contains metal sheets, metal rods, titanium sheets to build the rest of it.

**Comment by PerfectTangent** [comment]
completed with #7800
