### ISSUE TITLE
Blood miner, Leaper, and Drake do not have properly assigned sprites and are invisible in the game.

### ISSUE THREAD

**Issue by Akronymus-git** [unitystation/unitystation#5289]
### Detailed Bug Report
build: latest staging

### Steps to Reproduce

1. Find a blood miner, Leaper, or Drake.

**Comment by NoooneyDude** [comment]
Related to #5325.

**Comment by PetMudstone** [comment]
I have given the NPCs in question new prefabs that from testing, have working sprites. I think this issue can be closed now.

**Comment by PerfectTangent** [comment]
K.

**Comment by PetMudstone** [comment]
Scratch that, the mobs mentioned above do not have working sprites out of editor, even as local host. I do not know why their sprites only work in editor but I suspect it may be due to the large dimensions of said sprites. That doesn't explain why the xenomorph queen sprites work out of editor while having similar dimensions, however.
