### ISSUE TITLE
Allow players to pray to gods (AKA admins).

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5370]
## Description
Title. For some reason players are unable to pray to their gods (also known as admins) after admin tools got reworked. This is notable because one of the admin buttons brings up a "Player Prayers" window.

Admin buttons, button with the clasped hands is the "Player Prayers" button.
![image](https://user-images.githubusercontent.com/38266309/96675247-60919680-131f-11eb-8c14-d15c86af394a.png)

The Player Prayers window, empty of course.
![image](https://user-images.githubusercontent.com/38266309/96675325-85860980-131f-11eb-884f-9890901be727.png)

**Comment by Akbadain29** [comment]
For making it work in chat just prefix the message with the @ symbol, with the word attached to the @ symbol being whoever you are praying to. Probably should look up in a certain list, such that If the player types "@I can please have a banana", the message says you pray to the gods/pray to anyone who might hear you and not "Oh I, can please have a banana".

**Comment by had3z** [comment]
> 
> 
> For making it work in chat just prefix the message with the @ symbol, with the word attached to the @ symbol being whoever you are praying to. Probably should look up in a certain list, such that If the player types "@i can please have a banana", the message says you pray to the gods/pray to anyone who might hear you and not "Oh I, can please have a banana".


i really think that would confuse players a lot (# being whisper), and would uneccesarily clutter the prayers chat on the admin side via mistakes.

a better more RP-ing option would be to have an item(statue?) in the chapel, and for each prayer to use a consumable (incense stick?) . this would bring more interactions to the chaplain job.

Key points:
- praying to be done in the chapel, by interacting with a statue / altar / shrine
- altar should inherit from machine.cs, so that players can create altars themselves (example: altar of the frying pan, altar of the wrench, altar of the police baton. build list example: use 2 metal sheets for girder, wrench in place, ???, add specific item, use screwdriver to finish)
- praying should have a progress bar,just like construction
- praying should use up a consumable, traded by the chaplain himself . this should spawn in the chaplain's private quarters

**Comment by nok-ko** [comment]
> > For making it work in chat just prefix the message with the @ symbol, with the word attached to the @ symbol being whoever you are praying to. Probably should look up in a certain list, such that If the player types "@i can please have a banana", the message says you pray to the gods/pray to anyone who might hear you and not "Oh I, can please have a banana".
> 
> i really think that would confuse players a lot (# being whisper), and would uneccesarily clutter the prayers chat on the admin side via mistakes.
> 
> a better more RP-ing option would be to have an item(statue?) in the chapel, and for each prayer to use a consumable (incense stick?) . this would bring more interactions to the chaplain job.
> 
> Key points:
> 
>     * praying to be done in the chapel, by interacting with a statue / altar / shrine
> 
>     * altar should inherit from machine.cs, so that players can create altars themselves (example: altar of the frying pan, altar of the wrench, altar of the police baton. build list example: use 2 metal sheets for girder, wrench in place, ???, add specific item, use screwdriver to finish)
> 
>     * praying should have a progress bar,just like construction
> 
>     * praying should use up a consumable, traded by the chaplain himself . this should spawn in the chaplain's private quarters

Lots of prayers are done right after the person in question just majorly screwed up (spaced themself, etc.) – making prayer require a visit to the chaplain's office would make a lot of prayer interactions impossible. Prayer being available to anyone, at any time, makes a lot more fun RP/admemery possible since admins will see a lot more prayers.
