### ISSUE TITLE
Directional passables can leave a square even if they would bump into something in the same square.

### ISSUE THREAD

**Issue by Ruzihm** [unitystation/unitystation#5463]
Related TODO introduced in #5449

Example:
In this specific example the intake is not leavable from the top but it can still be pushed down even though it would bump into the canister
![intake moves through canister](https://i.imgur.com/gIl2ujl.gif)

**Comment by Ruzihm** [comment]
So just for the record, what would be the desired effect instead? That nothing gets pushed, correct?

**Comment by NoooneyDude** [comment]
If that disposal intake is unsecured, then I think the desired behaviour is for the canister to not be able to enter the same tile as the intake, because no side should be enterable. However, in the event that there is a movable, impassable object on top of another impassable object, I find it desirable to be able to move it out from that tile. All sides should be leavable.

Consider the situation when a player is on the same tile as a wall (perhaps by teleportation or during construction, or some other means). You would want the player to be able to leave the wall, and I think it should be the same for other objects (directional windows - and other similar objects -  being an exception; the window side should be impassable from any direction).

**Comment by Ruzihm** [comment]
I made the bottom enterable and leaveable just for the gif - so if it were some other object that should be non-enterable  and non-leaveable from every side but the bottom, what would the desired interaction be in that case?

**Comment by NoooneyDude** [comment]
Oh, sorry. I get ya now. Hmm. If anything should get pushed in this case, I suppose it would make more sense for the canister to be moved. Though, doing nothing might be more appropriate. I don't really have a solid answer.
