### ISSUE TITLE
New artifact effects

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#5627]
### Description

Right now artifacts have only one simple effect with two different variations. Let's make more. Check this [base class](https://github.com/unitystation/unitystation/blob/981b1c368b73145fb0f88d0be38dbcc8d5de7c18/UnityProject/Assets/Scripts/Objects/Research/Artifacts/Effects/ArtifactEffect.cs) to get started.
Here are some basic effects from baystation:
- [x] Randomly teleport user or whole area
- [ ] Stun user and everyone around.
- [ ] Heat/freeze area around artifact
- [ ] Emit oxygen/phoron/any other gas type.
- [ ] Generate force field around artifact.

We also can add something new:
- [x] Spawn some certain object from the pool. It can be bananas, gold or even magical-cult items.
- [x] Summon guardians (angry mobs). Might cause full-scale demon invasion.
- [ ] Resurrect corpses and turn them into zombies. Would be ideal if it whispers something like: "... make us whole..."

Just make sure to make protection from abuse. For instance, limit max things to spawn or add reasonable cooldown.

**Comment by ThatDan123** [comment]
I think Noooney added a teleport utility, so the first one should be relatively easy to add.

**Comment by ThatDan123** [comment]
Bit off topic for this post, but another artifact activation way could be "feeding" it items? Specific items or just anything could be good.

**Comment by NoooneyDude** [comment]
> I think Noooney added a teleport utility, so the first one should be relatively easy to add.

Yep see `TeleportUtils.ServerTeleportRandom()`, teleports the given object to a random point on an annulus.

**Comment by AtnerNT** [comment]
All of these and more are now implemented, bar the resurrection of corpses which would be best left until after all the mind changes.
Also to avoid any confusion, artifact effects have been reworked on the back end and now use this [base class](https://github.com/unitystation/unitystation/blob/develop/UnityProject/Assets/Scripts/ScriptableObjects/Research/Artifacts/Effects/ArtifactEffect.cs) instead of the one specified in the above issue.
