### ISSUE TITLE
Selling researched artifacts 

### ISSUE THREAD

**Issue by Macoron** [unitystation/unitystation#5628]
### Description
The idea is to add a new system to sell useless researched artifacts by cargo. This should create better connection between two departments and add more meaning to xenoarchaeology. 

If cargo would try to sell unresearched artifact, they would get just a few credits. We should add a new research console where scientists can make a report about artifacts effects and triggers from predefined dropdown list. This console should print report or generate report floppy disk.

Now if cargo will sell this artifact with floppy disk and report was correct, they will get very big bonus to artifact price. So researchers have motivation to study artifacts and cargo should figure out how to contain artifact and transport it safely to the shuttle.

**Comment by ThatDan123** [comment]
Would be nice to see if the dropdown list can be filled dynamically as new artifact types are discovered instead of showing all combinations at round start.

Guess this would be done by putting it in different machines in science, and then if the machine comes out with a result then the effect would be added to the dropdown list.

The detection machines could either be specific eg Heater detects heating effect, or we could say have 5 different machines and the artifact at start just picks a random machine which will identify all its characteristics/ random machine for each characteristic.
