### ISSUE TITLE
Magboots Action Button does not Update when Toggled

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5844]
### Environment
- Game Version: Staging 21010901, joined as client
- OS Version: Windows 10

### Details

The Magboots Action Button gets stuck displaying activated Magboots, even after the in-inventory sprite has changed.

### Steps to reproduce

1.  Put on Magboots
2.  Click the Action Button for the Magboots twice
3.  Notice that the Action Button sprite and the inventory sprite are different

### Bug in Action
![Bug_staging_21010901_button-sprite-update](https://user-images.githubusercontent.com/62223303/104091386-edb6fe00-5231-11eb-84fb-2c5143ee539a.gif)

**Comment by jackpotttt** [comment]
This is a networking issue, it can be easily fixed by making ItemMagBoots.isOn a syncvar. But I'm still learning how the networking works, is a syncvar ok for this? Since only one player actually needs the updated value for their HUD, should this be done with a message instead?

**Comment by corp-0** [comment]
since you can take off the boots and someone else can pick them up, I think the current state should be networked to everyone. What I find weird is that we have fought against ItemMagBoots a lot and I recall it being properly networked at some point. I'd have to take another look at the code.

**Comment by NoooneyDude** [comment]
I think this is a problem with `ItemActionButton` and not magboots themselves.

**Comment by NoooneyDude** [comment]
@jackpotttt in this case, a SyncVar isn't needed, because the effects only need to be applied serverside. SpriteHandler is also networked, so the client doesn't need to care about the state for sprites either.

I think this problem arises because the local client gets the latest SpriteHandler image after the action button invokes a server request to change state, but the client has not yet received the sprite update message from the server and so it displays an old sprite. This probably means it works fine in the editor but not when connected to a server.

**Comment by NoooneyDude** [comment]
One solution would be for `SpriteHandler` to trigger an event when the sprite SO changes, similar to the event for when sprite changes. `ItemActionButton` could then subscribe to that event if `useSpriteHandler` is checked, and update the button sprite SO accordingly.
