### ISSUE TITLE
Locker Populators trigger Twice on Round Start

### ISSUE THREAD

**Issue by Mute-Man** [unitystation/unitystation#5893]
### Environment
- Unity Editor, Latest Version on Repo as of 1/24/2021

### Detailed description of bug

Locker populators are triggering twice, causing lockers to spawn with twice the intended contents.

### Steps to reproduce

1.  Start round through Unity Editor Play Mode
2.  Go to the nearest Emergency Locker, since it is most apparent with Emergency Lockers (the red ones) 
3.  Open it and see that there are way more items than are listed to be spawned there in the populator for that locker

**Comment by Mute-Man** [comment]
Note: it isn't that the lockers have two components that populate the locker on round start.
It's one component triggering twice.

**Comment by Copern** [comment]
Looking through the code, as far as I can tell this only happens when the game is started in Host mode. GameManager.OnRoundStart is called twice, once on the server and and once on the client. Since the client is considered a server in Host mode, it goes through all the ISpawnServer objects and calls OnSpawnServer twice over. So for closets, this ends up spawning anything in the populator list to the closet twice.
