### ISSUE TITLE
Internals tank icon in new UI doesn't update when a usable tank is equipped.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#6069]
### Environment
- Game Version: 21021823
- OS Version: Windows 10

### Detailed description of bug
For some reason, the O2 tank icon in the new UI doesn't change if you have a usable internals tank in your external slots. This is especially odd because it changed before. This makes it impossible to properly tell if internals is turned on or not.
![image](https://user-images.githubusercontent.com/38266309/108572268-c50d3400-72c6-11eb-9757-fa71a37d1770.png)

### Steps to reproduce
1. Put oxygen tank in hands, pockets, or suit storage slot.
2. Notice that the internals tank icon doesn't change.

**Comment by MrAsbestos** [comment]
also it would be nice if you were able to enable internals by only clicking the icon, like this:
![image](https://user-images.githubusercontent.com/65787528/108572978-c04d7d80-72d0-11eb-8104-d2455664c6e0.png)

Rn you need to click exactly the oxygen tank:
![opera_eEV0mxEmuO](https://user-images.githubusercontent.com/65787528/108573149-32be5d80-72d1-11eb-9d36-02f64c645470.png)


My first instinct was to click the icon, I clicked the tubes instead of the tank, I was like "wtf is it broken?"
after some random clicking, I clicked exactly the oxygen tank, and finally enabled it.

**Comment by PetMudstone** [comment]
After a bit of testing, this only seems to happen as a client. As the host (including in editor) the filled tank icon appears, although only partially to indicate the capacity of the oxygen tank. Notably, ControlInternals has a method for altering the appearance of the filled sprite depending on the gas inside the gas tank. This is the same method that causes errors in #6139.

**Comment by NoooneyDude** [comment]
Still relevant? Somewhat confident this was working fine on staging recently. Related to #6139.

**Comment by PerfectTangent** [comment]
it broke again. there's an NRE being spammed endlessly on staging rn for when you toggle internals on:

```
NullReferenceException: Object reference not set to an instance of an object
UI.ControlInternals.Update () (at <74fb3e76fa934efabe441c455d8ffcd0>:0)
```
