### ISSUE TITLE
Ensure Addressables are written to an application data folder on all platforms B: 80

### ISSUE THREAD

**Issue by ShieldNavalny** [unitystation/unitystation#6072]
### Environment
- Game Version:  21021823
- OS Version:  Ubuntu Server 20.04 LTS

### Detailed description of bug
If AddressableCatalogues or LobbyAddressableCatalogues are defined to download in config.json then server will download all addressables in directory named com.unity.addressables which located in / (root directory of the OS). It is a security vulnerability.
All addressables should be located under gaming server files.

### Steps to reproduce
1. Define AddressableCatalogues  or LobbyAddressableCatalogues in config.json
2. Start up a server
3. ls -a /

**Comment by corp-0** [comment]
I'm elevating priority on this issue to **high**. Whoever can take a look at the addressables stuff, please check this issue.

**Comment by corp-0** [comment]
I'm elevating this issue to Bounty for 50 USD.

In order to consider it complete, the contributor must:
- Learn the addressable system.
- Make sure the addressable data is written to an application data folder in all 3 supported platforms.

In windows, that's already the case so data is written to ``C:\Users\<name>\AppData\LocalLow\Unitystation\unitystation\com.unity.addressables``.

In linux it is writting directly to ``/`` as stated in this issue, while it should be something like ``~/.var/app/org.unitystation.Stationhub/com.unity.addressables`` for flatpack and ``/.local/share/StationHub/com.unity.addressables`` for standard. 

Sadly I completely ignore what's the situation with MacOSX, but to consider this issue done, it should also write to a folder of the same kind as above.

**Comment by PerfectTangent** [comment]
increasing this bounty to 80 USD.

**Comment by craftxbox** [comment]
After thorough dives into the internals of the com.unity.addressables package, I found no reason as to why the files would *ever* be placed in /
I inspected existing server setups to see if there was any differences between them, I found that staging *did not* have this problem, and catalogues are being written to the correct ~/.config/unity3d path.
Inspecting Solidarity, I found that it DID have the problem, as did my own Wild Frontier server.
The only differences between staging and those two servers were that Staging is managed through Docker, where, the others are managed through Supervisor (supervisord.org)
After the conclusion of testing, it appears that supervisor *IS* at fault here, and executing the server through other means, such as directly through the terminal, or via systemd, yields correct behavior. 
No code changes are apparent at this time, however, I will be going through and updating the server installation/update helper scripts to *remove* supervisor in favor of systemd.
It was unclear whether or not it is possible to change the assetbundle caching directory after investigating, Best guess is `Caching.AddCache`, though, now that the main issue here is resolved I'm not sure if it's useful to begin with.

**Comment by craftxbox** [comment]
Sample systemd unit file:
```
[Unit]
Description=Unitystation server
Wants=network-online.target
After=network-online.target

[Service]
Restart=always
RestartSec=5s
KillSignal=SIGKILL
Environment="LD_LIBRARY_PATH=/home/unitystation/us13/Unitystation_Data/Plugins/x86_64"
User=unitystation
WorkingDirectory=/home/unitystation/us13
ExecStart=/home/unitystation/us13/Unitystation -batchmode -nographics -logfile serverlog.txt

[Install]
WantedBy=network-online.target
```

Paths and users will need to be substituted, but, should work drop-in to any existing supervisor-ran servers.
