### ISSUE TITLE
Aghost inventory does not function B:40

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6136]
![Screenshot at 2021-02-26 19-45-58](https://user-images.githubusercontent.com/55299415/109369853-29526980-786c-11eb-9004-ae0e9d497277.png)
linux - 4117
current aghost inventory does not completely work as intended. clicking on items just drops them rather than putting them into your hand. also cannot see items held in hand nor interact with them. the same goes for clothing under hardsuits

also to note. right click does not work in inventory viewer. I'm  guessing it doesn't work in aghost inv either however I have no way to verify it

additionally it would be nice to be able to pick up and pull items from the ground

**Comment by Pockets-byte** [comment]
also players cannot interact with at least some of the items they drop

**Comment by Pockets-byte** [comment]
aghost inventory doesn't work at all now. items just can't be interacted with

**Comment by PerfectTangent** [comment]
this issue is being promoted to bounty status. Evaluated at 40 USD.

**Comment by Aranclanos** [comment]
A few notes to reconsider re-opening this issue or make a new one with more clear goals:
-You can't pick up items from the floor or pull them - this was never implemented
-The inventory not working was fixed before the bounty was set
-The "also players cannot interact with at least some of the items they drop" comment wasn't confirmed or fixed
-You cannot see or interact with hidden inventory like pockets and undersuits, hands remain missing from the inventory window

Due to the amount of problems or new ideas in this particular issue, the goal is rather vague and the reward might have to be reconsidered.
