### ISSUE TITLE
Morgues show the opposite colors for bodies

### ISSUE THREAD

**Issue by Cboyjet4** [unitystation/unitystation#6170]
Small issue. Morgues show the opposite colors for bodies.

CURRENT

Red- Body still has life in it. (Also makes a constant beeping sound)

Green Body is 100% dead

CORRECT

Red- Body is 100% dead

Green- Body still has life in it.

**Comment by NoooneyDude** [comment]
While I realise it differs from /tg/, I think green for 100 percent dead makes more sense, because I associate green for "a-ok, no action required" whereas red means there is something wrong. Yellow, of course, is a warning, to let you know there are foreign objects inside.

That is the reason I chose those colours. If the community strongly feels one way or the other it can be changed.

**Comment by NoooneyDude** [comment]
Reopen if some has something to add.
