### ISSUE TITLE
item sizes has no effect B: 15

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#641]
# Preliminary information

## Category
BUG

## Bug: Release or Dev?
Develop

## BUG: Version
develop

# Report
## Current Behavior
even setting an item to "large" will still allow to put it in a pocket.

## Expected/Wanted/Requested Behavior
you should only be able to put small items into your pockets.

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour
1. set item size to large
2. start game
3. take item and put it in your pocket

**Comment by fomalsd** [comment]
Check out commented lines in UI_ItemSlot.CheckItemFit().
There are clientside checks for that (flawed though)
Also check and uncomment getItemSize() in ItemAttributes.
IIRC the problem was that the actual UI slots were too small for real DM data, and that CheckItemFit algo was also crappy, that's why I commented that out.

Note that you'd also need to implement serverside checks (in PNA.ValidateInvInteraction)

**Comment by DooblyNoobly** [comment]
Criteria: 

 - Resolve the bug
 - you should only be able to put small items into your pockets.

Bounty of 15usd will be paid on successful merge
