### ISSUE TITLE
Excessive blood production

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6493]
Excessive blood production.
![image](https://user-images.githubusercontent.com/6926225/118083543-387c9880-b413-11eb-858b-2dc6c6985feb.png)
A while later it had exceeded 280 percent.

No health-related interactions or events have taken place - this is a mostly-idle spawn on staging.

**Comment by jamessimo** [comment]
I’m taking a look at this

**Comment by corp-0** [comment]
how is that 100% calculated? Fixed max capacity for all creatures? Calculated by the amount of limbs?

**Comment by PerfectTangent** [comment]
is 100% the 'optimal' amount of blood to manage all bloodstream functions?

**Comment by jamessimo** [comment]
The full amount is 5,000. However when the player spawns they have 6,008ml. 
 
Still not sure about all these numbers as TG Station uses 560 as the max or nominal amount of blood. Still investigating. 

The health analyzer is accurate as it says I have 120% which is true. You can delete the blood from the circulatory base script at run time and it should go to normal (but slowly scale up again because the bones won’t stop making new blood)

edit: it seems to be re-agents get added forever by the respiratory system.

**Comment by jamessimo** [comment]
I am not exactly sure why but this bug has been resolved quite recently on staging. I noticed PR #6634 and #6620 added some thread locks tin regards to reagents in the blood which does coincide with my assumption that the math's is sound but we were having some weird race conditions as I could not accidently predict/time when blood would go up. 

Asking for someone to confirm and close this bug.

**Comment by jamessimo** [comment]
I have tested this extensively and can say this can be closed.
