### ISSUE TITLE
Lag after roundstart

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#6507]
There seems to be more lag than usual at round start. A cheap solution is to have most things start, say, 15 seconds earlier than roundstart (the moment players start spawning) to reduce the lag at this critical point.

**Comment by ThatDan123** [comment]
Think its due to all the populator contents spawning in (lockers and bags....)

To reduce it either spawn them before start, or only spawn them in on first open (e.g opening locker for the first time), does have the down side of the first open might be slightly delayed, but would be quick afterwards
