### ISSUE TITLE
can't mine diagonally

### ISSUE THREAD

**Issue by waffielz** [unitystation/unitystation#6685]
### Environment
- Game Version: all
- OS Version: all

### Steps to reproduce

1.  try and mine diagonally

**Comment by Fogapod** [comment]
Do you mean mining tile that has both sides blocked by other tiles? Because I can mine tiles that are not blocked diagonally.

What tool? Pickaxe?

Why do you think this is a bug? Is this how it works on other ss13 versions?
I think current behavior is correct. Even though there is currently a 1 pixel gap between diagonally connected tiles that you can see through I doubt you could mine entire tile through that.

Can you interact with objects that are blocked by tiles from 2 sides? This should be consistent.

**Comment by Aranclanos** [comment]
![GIF 10-Jun-21 10-12-49 AM](https://user-images.githubusercontent.com/701959/121531055-6fbf7480-c9d4-11eb-9e6d-f63bdb36dd0c.gif)
cant reproduce

**Comment by waffielz** [comment]
![can't mine](https://user-images.githubusercontent.com/15893891/121945231-8b52b400-cd21-11eb-85d3-5a5b5f51d595.PNG)

Can't mine a block if it's blocked from either side, it was possible before but was removed.

**Comment by DTraitor** [comment]
it was removed in this PR
https://github.com/unitystation/unitystation/pull/5447

**Comment by corp-0** [comment]
I think that's intended

**Comment by Aranclanos** [comment]
I think thats intended

**Comment by waffielz** [comment]
noooooo, bring it backkkk
