### ISSUE TITLE
Space background and you are unable to move after rejoining sometimes

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#6710]
### Environment
- Game Version: 21060314
- OS Version: Arch LInux

### Detailed description of bug

This could be reported already as this is an old bug but I could not find it.

Sometimes you only see space and can't move after rejoin.
![image](https://user-images.githubusercontent.com/22667809/120892712-4db2a480-c618-11eb-9e0d-3352089cbdae.png)

Things that work:
- chat
- rotation
- all of the UI and inventory (though if you drop thing it's gone)
- rest/stand

Things that do not:
- movement
- shift click for inspect (says space)
- right click (no items anywhere, the only thing it shows is you on the tile you are standing)

As soon as someone or something moves you, everything is back to normal.

Note: i cannot reproduce this on every map and every round, but when it happens this can go on for 2-3 rejoins in a row.

### Steps to reproduce

1. rejoin many times in a row
2. you are stuck
3. ask someone to move you
4. snap back to reality

**Comment by corp-0** [comment]
It only took me 3 relogins to trigger it. You get to hiddenpos. 
![image](https://user-images.githubusercontent.com/43683714/121732665-83480980-cac0-11eb-9828-3e696eeaf6a9.png)

**Comment by ThatDan123** [comment]
Reported on the discord:

-"hmm i wonder if that does have some correlation to the bug"

![image](https://user-images.githubusercontent.com/56727168/127999452-b178d54c-6295-4fe9-b7ec-6312438cb14f.png)

-"typed suicide on console, for some reason i can only teleport to butch because hes an Ancient Engineer? everyone else is in a wrong Z position somehow."

![image](https://user-images.githubusercontent.com/56727168/127999422-3cb4d969-e831-401b-9457-9fadddb24297.png)

Might be a related error:

Exception in OnStartClient:   at (wrapper managed-to-native) UnityEngine.Component.get_transform(UnityEngine.Component)
  at RegisterTile.FinishNetworkedMatrixRegistration (Tilemaps.Behaviours.Layers.NetworkedMatrix networkedMatrix) [0x00000] in <56e9ede862b946689697f0f9e9c565d9>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00010] in <60668eb8a8fe4c1fa70e7ec1e83ae4d8>:0 
  at UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) [0x00025] in <60668eb8a8fe4c1fa70e7ec1e83ae4d8>:0 
  at Tilemaps.Behaviours.Layers.NetworkedMatrix.FireInitEvents () [0x0001c] in <56e9ede862b946689697f0f9e9c565d9>:0 
  at Tilemaps.Behaviours.Layers.NetworkedMatrix.OnStartClient () [0x0004a] in <56e9ede862b946689697f0f9e9c565d9>:0 
  at Shuttles.MatrixSync.OnStartClient () [0x00006] in <56e9ede862b946689697f0f9e9c565d9>:0 
  at Mirror.NetworkIdentity.OnStartClient () [0x00026] in <e5701f2c5b0a4c7cb6a246f76b06c815>:0

**Comment by Aranclanos** [comment]
potato — 07/28/2021
okay, this might be completely unhelpful, but while in the stuck in space bug
I was able to move by toggling aghost on and off
after move a bit
this appeared
![image](https://user-images.githubusercontent.com/701959/129777238-7f032335-adc8-4949-9124-f0a76ef136b0.png)
this one airlock appeared, after moving downwards
![image](https://user-images.githubusercontent.com/701959/129777247-cb828592-0be1-41bc-b872-201ca12adb8c.png)

**Comment by Aranclanos** [comment]
DTraitor [ISS] — 07/26/2021
can't say how to reproduce but I have some info.
1. First time I met this bug before feature freeze was removed
2. It can happen with only one matrix. Station worked great but ancient station was bugged (maybe it was other bug connected with matrixes)
3. When you spawn in space you are actually on the station but client thinks that station in other place. (~15 tiles offset, happened on fall and outpost)
and you can't move
even as ghost
but you can be teleported

Station was almost empty when desynced

**Comment by Aranclanos** [comment]
Unitystation — 07/11/2021
![image](https://user-images.githubusercontent.com/701959/129777962-83fb4a62-f99a-4df6-8179-2f4075e69a3e.png)

**Comment by Aranclanos** [comment]
need a re-confirmation again in staging about this issue

**Comment by Fogapod** [comment]
I still regularly have this on solidarity, but not a single time on staging yet

**Comment by NoooneyDude** [comment]
Yeah, sounds good. The init changes are very welcome. May as well close.
