### ISSUE TITLE
Chat is unreasonably truncated 

### ISSUE THREAD

**Issue by Pockets-byte** [unitystation/unitystation#6727]
linux - staging

Currently chat has a maximum length, which is an issue, especially for antags
Easily reproducible, just by doing anything that makes "noise"

**Comment by Fogapod** [comment]
I cannot understand what this mean.
- width of chat log?
- width of text input for chat?
- character limit in chat text input?
- message count in log?

long messages are wrapped in chat:
![image](https://user-images.githubusercontent.com/22667809/120899471-92e6ce80-c638-11eb-8f4a-3c076b53e2ba.png)

How is this affecting antags specifically?

What fix are you actually expecting for this issue? Increasing amount of stored messages? To what amount?

If you mean message count in log i think that's intentional, to simulate memory. There were discussions multiple times:
https://discord.com/channels/273774715741667329/438708245268267028/782200545628520489

You probably want to store important information on paper or PDA notes.

**Comment by Pockets-byte** [comment]
"simulation of memory" by removing players access to things doesn't belong in a videogame
I walk away sometimes, and I hate not having a clue what happened for the 15 minutes I was away
sometimes if atmos is spazzing out, you can have your entire chat log cleared in under a minute

**Comment by wraith-54321** [comment]
being fair, antags can see their objectives again now but yeah, its really annoying how short the chat is, it should be longer or it should be time based if it is for simulating memory, I cannot count how many times the chat being so short has been a problem, it really just needs a rework

**Comment by Pockets-byte** [comment]
I don't think it should be simulating memory at all
I already have to remember things IRL
why should I need an ingame aid to help me forget easier

**Comment by PerfectTangent** [comment]
this isn't really a bug, more a feature request.

**Comment by Pockets-byte** [comment]
it seems like a bug to me, I'm no coder, but I always assumed this was a bug
I can't really imagine anyone actually intentionally implementing this

**Comment by corp-0** [comment]
closing since we have a fairly long chat "memory" now. It is a setting in the setting menu.
