### ISSUE TITLE
Lizard Character Creation

### ISSUE THREAD

**Issue by TheDoktorZ** [unitystation/unitystation#7068]
### Environment
- Game Version: 21071513

### Detailed description of bug
Lizards can have human hair and facial hair, but there is no "Edit" button to edit their colors, their color changes alongside the skin tone when that is edited.

**Comment by MaxIsJoe** [comment]
This is not a bug. This is an intended desgin.

**Comment by TheDoktorZ** [comment]
> This is not a bug. This is an intended desgin.

I was told otherwise on Discord to be honest, by Mudstone. Plus the Moth race has similar problems so I doubt it's intended design.
Also the problem for me is not with the fact they have hair, but they don't have color editing button for the hair and facial hair. They take the color of the skin tone.

**Comment by MaxIsJoe** [comment]
I worked on it. It's intended design that can be disabled with a checkbox.
Unless someone broke my own code and it's doing something else than it's intended to do (which is to make the bodyPart or hair match the skin's color) this as a bug at all.

Side note, Since I know that this will be brought up; "some SS13 codebases doesn't do this so we shouldn't do as well" is a  conversation that has been held twice already a few months ago. This is a visual design choice that at the time we agreed to leave it in as long as we have the ability to toggle it off and on. You can argue about what default setting for Lizards should be and if we should turn this into a server config file but this is not a bug and that is a discussion that should be held on our Discord server.
