### ISSUE TITLE
Objects Not Spawning On Join

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#7246]
![image](https://user-images.githubusercontent.com/56727168/128921647-63418473-b161-4298-8624-974a0ccdb19c.png)

Missing objects when joining a game, no client errors and server had no errors either:

![image](https://user-images.githubusercontent.com/56727168/128921731-1aee801f-5246-40b3-b988-820247235ba9.png)

Not sure if theres an easy way to reproduce, seems like it might have just been lockers/doors (but not all of them) or couldve just been coincidence

**Comment by corp-0** [comment]
does this still happen on the newest version of the game?

**Comment by PetMudstone** [comment]
![image](https://user-images.githubusercontent.com/38266309/129295529-f1f86859-916d-4624-89a4-4eeedc135e55.png)
Got onto staging just now and Square arrivals seems just fine.

**Comment by ThatDan123** [comment]
It doesnt seem to happen all the time, and it might be late joining in a round that has gone on a while.

**Comment by Aranclanos** [comment]
need a re-confirmation now that we did a huge update on both unity and mirror

staging only of course, unless soli gets a new build

**Comment by ThatDan123** [comment]
Was reported on the discord yesterday.

**Comment by Aranclanos** [comment]
need a re-confirmation again in staging

**Comment by Aranclanos** [comment]
AtnerNT — Today at 6:49 AM
![image](https://user-images.githubusercontent.com/701959/133616938-50678b22-54d1-4867-8c9e-34c5c046ea02.png)
![image](https://user-images.githubusercontent.com/701959/133616946-853932bc-f63d-40d4-885e-424bee6307a2.png)
  Spawned in on staging
  cant move
  and only like 5% of the objects have spawned

**Comment by Aranclanos** [comment]
Today I got it locally, the objects are there but disabled, it seems like the clients aren't receiving the SpawnMessage from the server

To test things around, I picked a random object and checked its `Guid assetId`, it was being saved properly to the list of objects to spawn, but that assetId never really arrived
The errors on the client are useless, they are just reporting that the spacematrix is missing, and this is because the OnStartClient() arent triggering, because they don't seem to arrive -or- the assetId that arrives is a different one.

**Comment by Aranclanos** [comment]
Second note, it doesn't seem like a wrong assetId is arriving since the mirror errors related to it dont show up

**Comment by Aranclanos** [comment]
Third note, I managed to reproduce it by logging in a couple times, this was after I restarted the round (originally I was testing why lighttubes were wrongly rotated after a server round restart)
