### ISSUE TITLE
Clicking on items that can hold other items on the ground with items doesn't put them in.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#7284]
### Environment
- Game Version: Staging 21081519 & Production 4121
- OS Version: Windows 10

### Detailed description of bug
When you click on an item that can hold other items such as backpacks or toolboxes with other items that can fit inside it, the items you click with on the storage itemss don't go into the latter. This is even if there is enough space for them.

### Steps to reproduce
1. Take off your backpack and put it on a floor. Make sure it has empty slots available.
2. Take a small item into your hand such as an ID or PDA and use it on the backpack.
3. Fail to put the small item in the backpack.

**Comment by Lizurt** [comment]
I can't fix the bug, but can share some debugging information.
This happens not in all cases and not with all items.

Case 1:
`WillInteract()` logic is wrong and blocks backpack's logic.
(here i'm trying to put a cigarette into a backpack)
![image](https://user-images.githubusercontent.com/42589308/129696599-6752e6ae-5d67-4178-809a-a14330ffb830.png)

Case 2:
A `ClientMessage` is not even sent. A backpack don't have a green or blue border when interacting.
That's why I don't know how to fix the bug, can't even find a reason of the bug.
