### ISSUE TITLE
please add UI scaling

### ISSUE THREAD

**Issue by techpriest154** [unitystation/unitystation#7687]
some method of altering the size of the UI, text box and menus that pop up

**Comment by Fr-Dae** [comment]
in order to bring some clarifications,
what we mean by UI scaling, could be summed up as a bar in the graphical parameter menu, with a multiplication or reduction factor of the interface.

The ideal would be to be able to scale AND move the boxes that compose the interface.

Large resolutions, small resolutions, those on TV, or simply people with poor eyesight, would be in great need of such an accessibility option.

**Comment by AtnerNT** [comment]
Added recently
