### ISSUE TITLE
Make Match boxes light matches

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#7716]
![image](https://user-images.githubusercontent.com/56727168/139944947-e8bcc424-3f5f-429f-b6a6-4d13123894d1.png)

Using a match on a match box should light it.

**Comment by Pottingmix** [comment]
Can I please be assigned to this??, I also found that when you drop a lit match it loses its light emitter target (might be a global thing for all lights)?

**Comment by PerfectTangent** [comment]
match functionality was completed in #7904. It just wasn't linked to close this issue. However, if there are bugs or problems with the implementation added in #7904, you are welcome to work on them. Feel free to open an issue covering the problem you described.

In the meantime, this issue is being closed.
