### ISSUE TITLE
Cannot maximize window completely

### ISSUE THREAD

**Issue by JacobSweeten** [unitystation/unitystation#836]
# Preliminary information
If I drag the window to the top of my screen to "snap" it to full screen or press the maximize button, it will, for a second, maximize, then it goes back to being slightly smaller than my actual screen size.

## Category
BUG

## Bug: Release or Development?
Beta V2, but I'm pretty sure it's been happening for a while on various versions.

# Report
## Current Behavior
See Preliminary Information

## Expected/Wanted/Requested Behavior
Window should snap to full screen

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Attempt to maximize the screen
2. ???
3. Not profit.

## OS used:
Windows

## System specifications
i3-3220, GTX 1060 6GB, 8GB RAM, 1920x1080 24" AOC monitor.

## Network
Not relevant

**Comment by JacobSweeten** [comment]
Slightly smaller window.

**Comment by fomalsd** [comment]
AFAIK it just gets window height and forces width to be strictly 16:9, that's why it extends onto the next screen when maximizing game on my 1280x1024 monitor

**Comment by DooblyNoobly** [comment]
The second time you attempt to go into fullscreen it works. Now try getting out of it...

**Comment by NinjaDanz3r** [comment]
I've had a look at this issue but I couldn't work it out so I'll post some information for the sake of posterity.

This problem occurs due to the ResponsiveUI component setting the resolution to a width and height divisible by two, to avoid tilemap stretching and tearing.

Instead of using `Screen.SetResolution(...)` in `UI\ResponsiveUI.cs` I have tested scaling the orthographic camera size by using the formula outlined in the following article:
https://blogs.unity3d.com/2015/06/19/pixel-perfect-2d/
The formula used to find the best orthographic size for a camera is `((Vert Resolution)/(PPUScale * PPU)) * 0.5`
In addition I also ensured that the camera was at an integer coordinate, that the camera had MSAA disabled and that the tilemap anchors for turf and walls were anchored at (0,0).
This still produced bleeding and tearing, so I must be missing something.
It does seem to be a common problem with Unity however, see below for other posts relating to this issue.

I also tried to scale the main cameras normalized viewport rectangle, where `normalized x = 768 / screen height` and `normalized y = 1080 / screen width` in order to scale the viewport to a 1080 by 768 resolution without changing the size of the window. This worked, but resulted in artifacts due to the camera not clearing the entire [screen](https://i.imgur.com/d3HudVJ.png).
This might be a good way to resolve this problem, but it'll need another camera in order to clear the artifacts and the viewport has to be put somewhere in the middle of the window.

Other related articles and posts:
https://forum.unity.com/threads/tilemap-has-tearing-between-tiles-even-with-pixel-snap.499154/
http://www.wickedsoulstudios.com/tile-tearing-in-unity-solution-finally-found/
