### ISSUE TITLE
Singularities sprites dont overlap properly

### ISSUE THREAD

**Issue by ilinm1** [unitystation/unitystation#8790]
### Environment
- Game Version: 
- OS Version: 

### Detailed description of bug
![image](https://user-images.githubusercontent.com/57045293/172222219-0117843a-df09-4769-9950-09802b2fe6c3.png)

### Steps to reproduce
spawn two singulooses near each other

**Comment by corp-0** [comment]
I don't recall this being a thing, do you know anything @jamessimo ?

**Comment by jamessimo** [comment]
@corp-0 I think this may have always been an issue because of the fact the warp effect is a material shader. The shader can access all layers but not any effects i think...  

Overlapping vertex shaders will have this issue. A way around it would be to make this a fragmentation shader but when I tested it I had issues where the effect wont work if the gameobject is not on screen.

**Comment by jamessimo** [comment]
https://forum.unity.com/threads/overlapping-transparent-shaders.1002148/ this also tackles the same issue but they used the node system where I just coded ours. It seems we can stack transparent shaders but someone who knows Unitys shaders better would have to advise.
