### ISSUE TITLE
Black Screen Glitch

### ISSUE THREAD

**Issue by potatoalienof13** [unitystation/unitystation#9002]
### Environment
- Game Version: 22072515
- OS Version: multiple 

### Detailed description of bug

![image](https://user-images.githubusercontent.com/51922130/180891891-712fbe88-7a23-4927-8c20-b0f1baa5506d.png)
Screen is black except for UI.
Errors spam the console, about 1 every frame.
example
```
Screen position out of view frustum (screen pos 1920.000000, 1080.000000, 1.000000) (Camera rect 0 0 1920 1080)
```
```
Screen position out of view frustum (screen pos 1037.000000, 717.000000) (Camera rect 0 0 1920 1080)
```
When the position is acquired with alt click, it is always (0,0,0)

### Steps to reproduce

1. Use fire extinguisher while floating in space

**Comment by potatoalienof13** [comment]
fuck i messed up markdown

**Comment by MaxIsJoe** [comment]
This is because you're moving at such a high speed that you're starting to enter the magical land of floating point errors and where the pixel perfect add-on's limit is.

A fix for this would be to force the client to always stay at 0,0 and move the world instead, however this is a none issue that I don't think it's worth tackling currently (at least until we make the map much more populated and bigger, and we expand upon shuttle gameplay)

**Comment by corp-0** [comment]
I think @Bod9001 fixed this, can't remember the PR and I probably forgot to tell him to bind the PR to this issue so it auto closes. Is that true, Bod? Maybe I dreamed about it.

**Comment by ThatDan123** [comment]
#9006
