### ISSUE TITLE
When opening air locks by movement the character cannot move for a while

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#901]
# Preliminary information
When opening air locks the character cannot move while its opening

## Category 
this a BUG

## Bug: Release or Development?
it was  on the Latest steam version Beta 5 

# Report
## Current Behavior
When opening air locks Your character seems to get stuck for a tiny bit of time

## Expected/Wanted/Requested Behavior
like in TG code You can move while the airlock is opening

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Find airlock 
2. Run into it to open it
3.Try to move away before the animation is finished (* is assuming it is the animation of the airlock)

## OS used:
Windows

## Network
server That is default on steam

**Comment by NinjaDanz3r** [comment]
This seems to be partly related to animation, as `OpenDoor()` in AirLockAnimator makes a call to `doorController.BoxCollToggleOff()` at the end, which turns off collision for the door. Putting the function at the start of `OpenDoor()` seems to alleviate the problem somewhat but not entirely.

I can see that pretty much everything preceding the call to `doorController.BoxCollToggleOff()` are coroutine calls which I presume are run somewhat concurrently so this might just be me seeing things.

**Comment by Bonfire** [comment]
I've noticed that removing the following line in PlayerMove.cs remedies the issue, but allows the player to walk through doors instantly:
https://github.com/unitystation/unitystation/blob/1163a4cda5f57f9006015f36bd2c1a85460adaee/UnityProject/Assets/Scripts/PlayGroups/PlayerMove.cs#L286

I'd suggest making it so that when the player opens the door, a collider is placed on the door so that they may not instantly move through it. If a collider already exists (and to my knowledge, a 2D Box Collider does, as @NinjaDanz3r pointed out), simply enable the collider until the door is fully opened. That way the restriction is placed on the opening door and not the player.

**Comment by fomalsd** [comment]
The important thing is regulating that on both server and client, so that if client gets modified to remove delay/colliders, server would still have it, rolling back client position on illegal move
