### ISSUE TITLE
[balancing] prevent troll spam

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9357]
block the repetition of similar words, to avoid chat spam, for example with emotes

**Comment by MaxIsJoe** [comment]
We already have a system for that.

**Comment by Fr-Dae** [comment]
then it is simply not currently functional.

**Comment by MaxIsJoe** [comment]
As far as I'm concerned, our spam prevention system seems to be working just fine.
The spam of other things like wind hitting things multiple times quickly is not something for us to worry about.

We're not going to program a stricter spam prevention system just because of a few edge cases that come as a result of gameplay.

**Comment by corp-0** [comment]
you have to give us examples, what is being spammed? How frequent is the spam? We have a chat spam prevention system, so without examples we have no way to tell if it is working as intended or not.

**Comment by Fr-Dae** [comment]
For example, the day sound emotes were introduced, like screams or fart noises... (a necessary feature, isn't it? /s )
the playtest session was literally unplayable because of the audio nuisance.

more recently, during another playtest, a scientist had fun creating literally 40 jukeboxes at full volume.
all knowing that they are completely buggy and unstoppable.
