### ISSUE TITLE
[ballencing] Jukebox spam prevention 

### ISSUE THREAD

**Issue by Fr-Dae** [unitystation/unitystation#9358]
Blocked the appearance of jukeboxes too close to each other, to avoid trolls spamming the station with music.

**Comment by MaxIsJoe** [comment]
No, we should not block that.
That's up for the admins to decide to keep or punish players for.

**Comment by AtnerNT** [comment]
I do not see this as an issue. A player should be able to build jukeboxes wherever they like so long as they can produce the materials and circuit boards to do so. There should not be any artificial restrictions on why a player can not build a machine, and trolling is a natural part of the game. We do not remove space lube because clowns like using it to slip people.

**Comment by AtnerNT** [comment]
Dammit Max you beat me by 17 seconds

**Comment by PerfectTangent** [comment]
agreed, closing.

**Comment by Fr-Dae** [comment]
So added work to the admins, when a function would simplify their work?

Also, what about the parts where the admin is not present, the nuisance is still there. 

> A player should be able to build jukeboxes wherever they like so long as they can produce the materials and circuit boards to do so

I'm just talking about a mechanism that would prevent several jukeboxes from working at the same time, not necessarily their appearance, the problem is the addition of several sounds, not the visual itself.
