### ISSUE TITLE
Implement improved Logging

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#943]
# Preliminary information

## Category
Feature Request

# Report
## Current Behavior
Logging can be a little stupid currently.

## Expected/Wanted/Requested Behavior
Look at Python's logging package and see how we could implement something similar.

See quote by PJB:

>     logging.getLogger("websockets").setLevel(logging.WARNING)
>     logging.getLogger("urllib3").setLevel(logging.WARNING)
>     logging.getLogger("bottom").setLevel(logging.WARNING)
>     logging.getLogger("github3").setLevel(logging.WARNING)
>     logging.getLogger("discord").setLevel(logging.WARNING)
>     logging.getLogger("asyncio").setLevel(logging.INFO)
> I have this at the bottom of my log setup file on my discord bot
> I know ones like discord.py have lots of debug logs
> I have DEBUG enabled on my bot's root logger, but I tell the sub loggers to be limited to warnings/info
> Asyncio for example reports "you forgot an await you nob" with logging

**Comment by PJB3005** [comment]
Just for more clarity:

SS13 is *really* bloody complicated and there are tons of systems everywhere. Because of this the traditional debug/info/warning/error/fatal system quickly breaks down because debug logs get so verbose you get flooded with everything, even when you want to only debug a specific system.

So, there should be categories which each have their own logging treshold and such.

**Comment by Dunkhan** [comment]
maybe use log4net?
https://logging.apache.org/log4net/release/features.html

**Comment by krille90** [comment]
Adding to that: 

I think it would be good if we have a centralised tool with which we can control visual debugging (e.g.  gizmos) and logging.

Probably also need to be persistent, otherwise all configurations to it would reset after recompiling.

**Comment by fomalsd** [comment]
Fixed by @Bod9001
