### ISSUE TITLE
Chat UI Overhaul B: 70

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#948]
# Preliminary information

## Category
TODO

# Report
## Current Behavior
The current Chat is very basic and should be improved.

## Requested Behavior
- [ ] ~~Name of players should be clickable, e.g. right-click menu~~
- [x] Use the "T"-key for a single message. 
-  [ ] ~~Hitting "Enter" should leave the focus on chat (you can keep writing messages).~~
  - [x] Hitting ESC or clicking outside of the chat window should lose the focus.
- [x] Mouse-over test over channel icon with the name of the channel (it's currently difficult to tell just by the icon)
- [x] Create a chat entry prefab (or modify the existing one if it exists?) that will be instantiated and used within the chat window content area
  - [x] Should be universal and support all entries/notifications and reporting in the chat window as seen on a normal ss13 game
- [x] Turn the chat window into a scrollable view
- [x] Remove it entirely from the right panel as the right panel will be removed soon.
- [ ] ~~Have the content object expand as more chat entry objects are added to the end~~
- [ ] ~~Add the drag-able component to the new chat window so it can be position anywhere. (See GUI_PlayerOptions for an example of the drag-able component in use)~~
- [x] Make the channel selection more user friendly. (Atm it is hard to know what channel you are on.)
- [x]  Switch channel automatically to ghost when dead

**Comment by DooblyNoobly** [comment]
`Ability to chat continously without hitting "t" all the time` would be difficult because of WASD input

**Comment by krille90** [comment]
if you want to have a long chat, you could just hit enter and type (like in other games).

Then, if you don't want to chat anymore, just press ESC or exit chat mode.

**Comment by DooblyNoobly** [comment]
What about Enter to chat and then enter to send (close chat) (no line breaks). Or make shift+enter a line break while you are chatting. But I think we want to avoid walls of text where possible in the chat so not allowing line break would be better.

**Comment by krille90** [comment]
agreed, no line breaks needed.

**Comment by DooblyNoobly** [comment]
Bounty has been postponed for this (moving funds to shuttle controls)

**Comment by DooblyNoobly** [comment]
Any objections to moving the chat to the left side of the screen and making something similar to Rust Chat?
![image](https://user-images.githubusercontent.com/20813925/35773713-9d7fd61e-09a5-11e8-8071-6b1e35384fb7.png)

**Comment by DooblyNoobly** [comment]
Bounty of 70 usd will be awarded to the contributor on a successful merge of all completed criteria above

**Comment by Jibbajabbafic** [comment]
Some things addressed in #1568 

Will attempt a couple more things

**Comment by chairbender** [comment]
@Jibbajabbafic still working on this?

**Comment by Jibbajabbafic** [comment]
Apologies for my absence. I'm going to work on this this week and try to tick a few more things off.

**Comment by Jibbajabbafic** [comment]
Made some progress but won't be able to work on this for the next 2 weeks so if anyone wants to take over please feel free. I'll finish what I've got when I'm back.

**Comment by DooblyNoobly** [comment]
Any updates on this @Jibbajabbafic ?

**Comment by Jibbajabbafic** [comment]
Been a busy few weeks, I'll start working on this again

**Comment by Jibbajabbafic** [comment]
I've hogged this for way too long, someone else can finish it (I don't think there's much to do)

**Comment by JaytleBee** [comment]
I think I'll have a go at this.

**Comment by dapocalypse** [comment]
You beat me too it

**Comment by JaytleBee** [comment]
I did wait 20h

**Comment by dapocalypse** [comment]
You did claim it first

**Comment by JaytleBee** [comment]
I think I'm probably not cut out for this after-all, @dapocalypse you can do this if you still want it.

**Comment by dapocalypse** [comment]
Epic!

**Comment by dapocalypse** [comment]
@krille90 I'm a bit confused what the first checkbox is asking me to do, does it want something to pop up when I click it or.

**Comment by Aranclanos** [comment]
the players names on the chat should have interactions, for example an AI tracking with its camera, a ghost orbitting, admin tools, etc

**Comment by dapocalypse** [comment]
Do I have to list these interactions or just make a menu

**Comment by DooblyNoobly** [comment]
I'm going to take this one over

**Comment by DooblyNoobly** [comment]
Just finished a quick mock up experiment with chat bubbles above the player to see if it looks and feels alright:

![ChatbubbleMockup](https://user-images.githubusercontent.com/20813925/62524309-b5f79a00-b878-11e9-99bf-26adc111ff7b.gif)

![image](https://user-images.githubusercontent.com/20813925/62524752-82693f80-b879-11e9-9e3c-df6d4f7da22b.png)

I have ideas on where to take it from here so I'm going to set up some chat options that allows you to toggle the chat bubbles on or off and an easier way to select channels.

**Comment by fomalsd** [comment]
the idea is nice, but in my opinion: 
- width should be limited to around 3 tiles (height is alright)
- it needs to look more ss13y (pixelated frame perhaps), at the moment style seems a bit off
- we seem to stick with dark theme approach in general, so bubbles could also be bright text on darker bg (but that's debatable)

**Comment by DooblyNoobly** [comment]
Cool, Ill post more screens after I finish the visuals

**Comment by DooblyNoobly** [comment]
I think these two criteria should be scrubbed:

1. Have the content object expand as more chat entry objects are added to the end 
2. Add the drag-able component to the new chat window so it can be position anywhere. (See GUI_PlayerOptions for an example of the drag-able component in use)

for 1 I think I've set a pretty decent size that works well with the chat stream
and 2 I don't see how this will benefit as we don't have dockable windows for any of the other stuff yet. This should be a feature for later on when the dockable stuff is determined. That way when you are dragging the chat feed it can snap to parts of the game window instead of just free floating where ever.

**Comment by DooblyNoobly** [comment]
I'm wondering what options should be available under the right click menu: 

`Name of players should be clickable, e.g. right-click menu`

I guess I can have copy as one

**Comment by DooblyNoobly** [comment]
Right I think we should leave right clicking until we actually have AI or even the admin tools (we don't even have admin login for ingame yet as its all done via a portal). We could even make the start of right click menu for ghost follow which should be a separate issue also. There has been a lot of work done on chat since this job was opened so I think the Chat UI Overhaul is sufficient enough for 0.4 alpha release. 

Work that I've completed:
- Removed from right panel
- Resize of chat stream
- Added scroll bar
- Refactored ChatSystem code so that all chat usage is done now via the Chat API
- Added chat bubbles
- Added chat bubble customization
- Added verbs
- Added channel colors

Closing this ticket and will make separate TODOs for admin, AI and Ghost options after 0.4
