### ISSUE TITLE
UI & Window Ideas

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#949]
# Idea Collection Issue

The current UI is very basic and has its limitation. This issue should be used as a general issue to collect ideas for a new UI. Wishes, thoughts and ideas are welcome here.

Current ideas:
- [x] Dockable & draggable tabs.
- [x] Chat window as a standalone with an option to hide it.
- [x] Abolish the right panel completely and Redesign the whole UI

**Comment by DooblyNoobly** [comment]
Yes and the questions should be asked: Should we move away from the right panel all together?

**Comment by PJB3005** [comment]
Yes please @DooblyNoobly.

The right panel has like, the chat and verbs. Verbs shouldn't exist and anything the non-chat part of the panel stands for can be moved somewhere more intuitive.

Chat you can just have transparently overlaying the top right corner or whatever. Just cut the amount of chat feedback on things like interaction and you can shrink the chat significantly without losing much.

**Comment by DooblyNoobly** [comment]
Yep I agree. For all other things we should just have a normal options button somewhere that opens up a floating window.

**Comment by Whiteanon** [comment]
These ideas may be beyond what this topic entails focusing more on windows used for interaction with the stations various systems.

Windows: if possible maybe a border flair like that of different operating systems themed by the devices typical department user, maybe a clunky yellow industrial window border for engineering computers ect.
UI
Player: the players basic ui ie. the side bar should be displayed in a way that makes sense possibly hotkeyed where applicable. The tabs separating ooc,ic,admin,ect. make sense but it may make more sense to have common actions consolidated in a way that makes them easily accessible.
Interaction windows: when interacting with systems rather than displaying the information as a table of various numbers and buttons the interface should be more graphical in example hacking a door maybe display wires visually and instead of cut/mend toggle buttons visibly show the colored wire as being severed or whole a horizontal view of each color wire being clickable for cut mend with a pulse button on the end of each length would likely take up less room on the screen than the current table setup. And I feel like a graphical representation could make most if not all terminals not only look better but also be more user friendly.

**Comment by Epicworlds** [comment]
Yes I made a sketch of this idea last year, i totally support getting rid of the right panel. It was just a BYOND UI limitation anyway, and we are in unity

**Comment by HeadClot** [comment]
What about Radial menus?

**Comment by DooblyNoobly** [comment]
Yea I like those ideas @Whiteanon I think also it opens up the possibility of mini games also. Like you said with the wires instead of just text and buttons. 

@HeadClot that was actually suggested by @MrLeebo a few months ago and we thought it was a good idea. Definitely worth a prototype. He had a reference image too (i think from sims?)

**Comment by HeadClot** [comment]
@DooblyNoobly - Did not know that @MrLeebo made that suggestion. That is very good to know. Glad some one else supports the idea of radial menus. :)

**Comment by chilisource** [comment]
@DooblyNoobly There are already a lot of different frameworks for windowing system design out there, we might be better off just recreating one of those, such as the X Window System. 

There is a lot of UI theory about it online, but I think a Windowing System that utilizes the WIMP (windows, icons, menus, pointers) paradigm could be very beneficial and versatile, and give us a framework that we can use to create windows and tabs for anything we need. 

See: 
[Wikipedia on Windowing Systems](https://en.wikipedia.org/wiki/Windowing_system))

[Wikipedia on WIMP UI Design Paradigm](https://en.wikipedia.org/wiki/WIMP_(computing))

**Comment by fomalsd** [comment]
Copying my idea from general-dev channel
![default](https://user-images.githubusercontent.com/10403536/37869899-2b2d3c20-2fd2-11e8-8ef8-03bc1d4b673e.png)

**Comment by DooblyNoobly** [comment]
yeah that looks really good

**Comment by krille90** [comment]
Seems to be implemented now.
