### ISSUE TITLE
Redesign Input system B: 70

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#953]
# Preliminary information

## Category
TODO

# Report
## Current Behavior
Input stuff is currently hardcoded and scattered throughout the codebase

## Expected/Wanted/Requested Behavior

- Avoid hardcoded constructions like this one:
```
			if (azerty)
			{
				if (Input.GetKeyDown(KeyCode.A))
				{
					Drop();
				}
			} else {
				if (Input.GetKeyDown(KeyCode.Q))
				{
					Drop();
				}
			}
```
- Centralize all input controls (key/mouse/touch) in some sort of input manager?
- Allow custom keybindings

Suggestions are welcome.

**Comment by maxphillipsdev** [comment]
We should have I think a scriptable object with a custom inspector. Would have a list or dictionary of some kind in the inspector where you can specify a name and corresponding input or set of inputs for each input we need. Since it is a scriptable object we can load it at runtime and swap them out when needed.

**Comment by Puzzlemaker1** [comment]
the Weapons script has some hardcoded inputs, I made a ticket about it.

**Comment by Jibbajabbafic** [comment]
Working on this

**Comment by DooblyNoobly** [comment]
Bounty added for the completion of this request.

Criteria:
 - Complete all of the requested criteria in the issue description

Bounty of 70usd will be paid to the contributor on a successful merge of the features listed in the criteria

**Comment by Jibbajabbafic** [comment]
I might as well finish what I started, claim
