### ISSUE TITLE
[BUG] People randomly being sideways.

### ISSUE THREAD

**Issue by eurtod** [unitystation/unitystation#9753]
### There is no other issue reporting the same problem.

- [X] I have searched the existing issues

### Game Version

23032711

### I was

Client

### OS

Windows 8, 10, 11

### What happened?

Sometimes people will randomly appear sideways but otherwise walk, talk, interact, etc. the same. Throwing them typically fixes the issue. It's just a very annoying visual bug.

### What should have happened instead?

People should only be sideways if they are lying down.

### Steps to reproduce the issue

1. Don't know it seems to be random when playing.

**Comment by MaxIsJoe** [comment]
I don't know if #9863 will fix this issue because I'm unable to replicate it solo, and I also have a feeling it might have to do with how the new movement system rotates players when thrown.

It's very unlikely, but if it does get fixed; please close this issue after a month or two or when a player finds a way to replicate this issue and the new laying down safe-guard kicks in.
