### ISSUE TITLE
Chat can't handle more than 65000 symbols

### ISSUE THREAD

**Issue by fomalsd** [unitystation/unitystation#983]
# Preliminary information

## Category
BUG

## Bug: Release or Development?
Dev

# Report
## Current Behavior
Chat window corrupts text and exceptions are thrown if more than 65000 symbols are on screen

## Expected/Wanted/Requested Behavior
Chat should handle megawalls of text without a hiccup

## Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:
1. Post more than 65k symbols total in chat
2. See exceptions and corrupted letters in chat window

## OS used:
Windows

## System specifications
Irrelevant

## Network
Irrelevant

**Comment by Bonfire** [comment]
I can't seem to reproduce this bug. I'm able to send chat messages with anywhere from 1 to 1,000,000 characters in the chat without issue. I'm unsure whether or not the messages are being truncated and not throwing any errors as a result. In your issue you state that you must post more than 65k (I assume 65535, the max number of vertices for something like this) symbols total. Either I'm not able to post that many symbols because my messages are being chopped off, the chat is being chopped past a certain point, or I just haven't been able to reach that many messages. Would you be able to provide a string or gif/video of the issue to help reproduce it?

**Comment by fomalsd** [comment]
@Bonfire Sorry for the late reply.
In PlayerSync.cs at line 339: replace 
`//			Debug.Log( $"NextState: src={state} proposedPos={newState.WorldPosition}\n" +
//			           $"mAtPoint={matrixAtPoint.Id} change={matrixChangeDetected} newState={newState}" );`
with 
`			PostToChatMessage.Send($"NextState: src={state} proposedPos={newState.WorldPosition}\n" +
			                       $"mAtPoint={matrixAtPoint.Id} change={matrixChangeDetected} newState={newState}", ChatChannel.System);`
So that it would print a lot of debug text to the chat window and walk around on station.
Actually I think that it breaks after much less than 65000 symbols, but it's mentioning 65000 vertices in resulting exception spam:
![gif](https://user-images.githubusercontent.com/10403536/39691071-ce9004d6-51cb-11e8-8d12-bdf8fd809e8e.gif)

**Comment by DooblyNoobly** [comment]
separated into objects so this can't happen again
